import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Free Bank Account Opening Resolution Generator — Company Bank Account India",
  description:
    "Generate a board resolution for company bank account opening instantly. Specify authorised signatories, signing authority (single/joint), and branch details. Free, bank-ready format accepted by all Indian banks.",
  keywords: [
    "bank account opening resolution company",
    "board resolution bank account opening India",
    "company bank account resolution format",
    "authorised signatory resolution bank",
    "bank resolution private limited company",
    "current account opening resolution",
    "SBI company account resolution",
    "HDFC company account resolution",
    "ICICI bank company resolution",
    "joint signatory bank resolution",
    "single signatory bank resolution",
    "bank resolution generator free",
    "certified true copy bank resolution",
    "resolution for new bank account company",
    "Companies Act bank account resolution",
  ],
  alternates: {
    canonical: "https://compliancesearch.in/tools/documents/bank-resolution",
  },
  openGraph: {
    title: "Free Bank Account Opening Resolution Generator",
    description:
      "Generate a bank-ready board resolution for company current account opening. Free, instant, accepted by all Indian banks.",
    url: "https://compliancesearch.in/tools/documents/bank-resolution",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Free Bank Account Resolution Generator",
    description: "Company bank account opening resolution — free, instant, bank-ready.",
  },
};

export default function BankResolutionLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "SoftwareApplication",
                "name": "Bank Account Opening Resolution Generator",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web Browser",
                "url": "https://compliancesearch.in/tools/documents/bank-resolution",
                "description":
                  "Free online board resolution generator for company bank account opening. Supports single and joint signatory authority. Accepted by SBI, HDFC, ICICI, Axis and all major Indian banks.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "INR" },
                "creator": { "@type": "Organization", "name": "ComplianceSearch.in", "url": "https://compliancesearch.in" },
              },
              {
                "@type": "FAQPage",
                "mainEntity": [
                  {
                    "@type": "Question",
                    "name": "What documents does a bank need to open a company current account?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "Banks require: Board Resolution authorising account opening and signatories, Certificate of Incorporation, Memorandum & Articles of Association, PAN card of the company, KYC documents of directors and authorised signatories, and address proof of registered office.",
                    },
                  },
                  {
                    "@type": "Question",
                    "name": "What should a bank account opening board resolution contain?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "The resolution must include: company name and CIN, bank name and branch address, names and designations of authorised signatories, signing authority (single or jointly), scope of operations (deposits, withdrawals, cheques, NEFT/RTGS), and the date and quorum of the board meeting.",
                    },
                  },
                  {
                    "@type": "Question",
                    "name": "Is this resolution accepted by all banks in India?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "Yes. The resolution generated by ComplianceSearch.in follows the standard format recognised by all scheduled banks in India including SBI, HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, Punjab National Bank, and others.",
                    },
                  },
                ],
              },
            ],
          }),
        }}
      />
      {children}
    </>
  );
}
