import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import * as dotenv from "dotenv";
import { RULE_DOCUMENTS } from "../lib/rule-documents";
dotenv.config({ path: ".env.local" });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const c = (obj: object) => JSON.stringify(obj);
const always = c({ op: "always" });
const field = (field: string, cmp: string, val: unknown) => c({ op: "field", field, cmp, val });
const or  = (...conditions: object[]) => c({ op: "or",  conditions });
const and = (...conditions: object[]) => c({ op: "and", conditions });

const orRaw  = (...conditions: object[]) => ({ op: "or",  conditions });
const andRaw = (...conditions: object[]) => ({ op: "and", conditions });
const fieldRaw = (f: string, cmp: string, val: unknown) => ({ op: "field", field: f, cmp, val });

const RULES = [
  // ─── CENTRAL TAX ───────────────────────────────────────────────────────────
  {
    ruleKey: "pan",
    name: "PAN Registration",
    shortName: "PAN",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Permanent Account Number — mandatory tax identity for all businesses.",
    howToComply: "Apply online at NSDL/UTIITSL portal. Company/LLP requires a separate PAN.",
    frequency: "one_time",
    dueDate: null,
    penalty: "₹10,000 penalty if PAN not quoted where required (Section 272B)",
    registrationLink: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    priority: "critical",
    tags: "tax,registration,mandatory",
    conditionJson: always,
  },
  {
    ruleKey: "itr",
    name: "Income Tax Return (ITR) Filing",
    shortName: "ITR",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Annual income tax return filing — mandatory for every business entity.",
    howToComply: "File ITR-3/4/5/6 based on entity type. Tax audit required if turnover exceeds ₹1 Cr (business) or ₹50L (professional).",
    frequency: "annually",
    dueDate: "31 July (non-audit) | 31 October (audit applicable)",
    penalty: "₹5,000 late fee; interest @1% per month on tax due",
    registrationLink: "https://www.incometax.gov.in",
    priority: "critical",
    tags: "tax,annual,mandatory",
    conditionJson: always,
  },
  {
    ruleKey: "tds_deduction",
    name: "TDS Deduction & Deposit",
    shortName: "TDS",
    category: "central_tax",
    authority: "Income Tax Department (TRACES)",
    description: "Tax Deducted at Source on salary, rent, professional fees, and contractor payments.",
    howToComply: "Obtain TAN (Form 49B). Deposit TDS by 7th of every month. File quarterly returns (24Q/26Q).",
    frequency: "monthly",
    dueDate: "7th of every month (deposit) | 31 Jul/Oct/Jan/May (quarterly return)",
    penalty: "1% per month interest for late deduction; 1.5% for late deposit; penalty = TDS amount",
    priority: "critical",
    tags: "tax,tds,monthly",
    conditionJson: or(fieldRaw("employeeCount", ">", 0), fieldRaw("turnoverLakhs", ">", 20)),
  },
  {
    ruleKey: "advance_tax",
    name: "Advance Tax Payment",
    shortName: "Advance Tax",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Pay advance tax in quarterly instalments when estimated tax liability exceeds ₹10,000.",
    howToComply: "Pay by 15 Jun (15%), 15 Sep (45%), 15 Dec (75%), 15 Mar (100%).",
    frequency: "quarterly",
    dueDate: "15 Jun, 15 Sep, 15 Dec, 15 Mar",
    penalty: "Interest @1% per month under Section 234B & 234C for shortfall",
    priority: "high",
    tags: "tax,quarterly,advance",
    conditionJson: field("turnoverLakhs", ">", 10),
  },
  {
    ruleKey: "gst_reg",
    name: "GST Registration",
    shortName: "GST Reg.",
    category: "central_tax",
    authority: "GST Department (GSTN)",
    description: "Goods & Services Tax registration — mandatory when turnover exceeds threshold or for inter-state supply.",
    howToComply: "Apply on GST portal. Goods: ₹40L+, Services: ₹20L+ (special states: ₹10L). Inter-state supply: no threshold.",
    frequency: "one_time",
    dueDate: null,
    penalty: "10% of tax evaded (min ₹10,000) | Deliberate evasion: 100% penalty",
    registrationLink: "https://www.gst.gov.in/",
    priority: "critical",
    tags: "gst,registration,indirect tax",
    conditionJson: or(fieldRaw("turnoverLakhs", ">=", 20), fieldRaw("hasImportExport", "==", true), fieldRaw("hasMultipleStates", "==", true)),
  },
  {
    ruleKey: "gstr1",
    name: "GSTR-1 (Outward Supplies Return)",
    shortName: "GSTR-1",
    category: "central_tax",
    authority: "GST Department",
    description: "Monthly/quarterly return for outward supplies (sales).",
    howToComply: "Monthly (turnover > ₹5Cr): by 11th of next month. Quarterly (QRMP): by 13th after quarter end.",
    frequency: "monthly",
    dueDate: "11th of next month (monthly) | 13th after quarter end (QRMP)",
    penalty: "₹200/day (₹100 CGST + ₹100 SGST), max ₹5,000",
    priority: "critical",
    tags: "gst,return,monthly",
    conditionJson: or(fieldRaw("turnoverLakhs", ">=", 20), fieldRaw("hasImportExport", "==", true)),
  },
  {
    ruleKey: "gstr3b",
    name: "GSTR-3B (Summary Return & Tax Payment)",
    shortName: "GSTR-3B",
    category: "central_tax",
    authority: "GST Department",
    description: "Monthly summary return with GST tax payment for all registered businesses.",
    howToComply: "Monthly: by 20th of next month. QRMP scheme: 22nd/24th of month after quarter.",
    frequency: "monthly",
    dueDate: "20th of next month",
    penalty: "₹50/day (nil return: ₹20/day); interest @18% p.a. on late tax payment",
    priority: "critical",
    tags: "gst,return,monthly,tax payment",
    conditionJson: or(fieldRaw("turnoverLakhs", ">=", 20), fieldRaw("hasImportExport", "==", true)),
  },
  {
    ruleKey: "gstr9",
    name: "GSTR-9 (Annual GST Return)",
    shortName: "GSTR-9",
    category: "central_tax",
    authority: "GST Department",
    description: "Annual GST return — consolidated summary of the full financial year.",
    howToComply: "File by 31 December for the previous FY. Optional for turnover below ₹2 Crore.",
    frequency: "annually",
    dueDate: "31 December",
    penalty: "₹200/day (max 0.5% of turnover)",
    priority: "high",
    tags: "gst,annual,return",
    conditionJson: field("turnoverLakhs", ">=", 200),
  },
  {
    ruleKey: "gstr9c",
    name: "GSTR-9C (GST Reconciliation Statement)",
    shortName: "GSTR-9C",
    category: "central_tax",
    authority: "GST Department",
    description: "Reconciliation statement certified by CA/CMA for businesses with turnover above ₹5 Crore.",
    howToComply: "Get certified reconciliation statement from CA/CMA. File by 31 December.",
    frequency: "annually",
    dueDate: "31 December",
    penalty: "₹200/day (max 0.5% of turnover)",
    priority: "high",
    tags: "gst,audit,annual",
    conditionJson: field("turnoverLakhs", ">=", 500),
  },

  // ─── MCA / ROC ─────────────────────────────────────────────────────────────
  {
    ruleKey: "roc_incorporation",
    name: "Company/LLP Incorporation (ROC)",
    shortName: "ROC Registration",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Registration of Company or LLP with MCA — required once at formation.",
    howToComply: "File SPICe+/FiLLiP form on MCA21 portal. DIN, DSC, MOA, AOA required.",
    frequency: "one_time",
    dueDate: null,
    penalty: null,
    registrationLink: "https://www.mca.gov.in",
    priority: "critical",
    tags: "mca,registration,roc",
    conditionJson: field("businessType", "in", ["llp","opc","pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "aoc4",
    name: "AOC-4 — Financial Statement Filing",
    shortName: "AOC-4",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Annual filing of Balance Sheet and P&L with MCA by all companies.",
    howToComply: "File within 30 days of AGM (or 6 months from FY end, whichever is earlier) using AOC-4 form.",
    frequency: "annually",
    dueDate: "30 days after AGM (typically by 29 October)",
    penalty: "₹100/day delay (no cap)",
    priority: "critical",
    tags: "mca,annual filing,financial statements",
    conditionJson: field("businessType", "in", ["opc","pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "mgt7",
    name: "MGT-7 / MGT-7A — Annual Return",
    shortName: "MGT-7",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Annual return with details of directors, shareholders, and meetings.",
    howToComply: "File within 60 days of AGM. OPC/Small companies: MGT-7A. Others: MGT-7.",
    frequency: "annually",
    dueDate: "60 days after AGM (typically by 28 November)",
    penalty: "₹100/day delay (no cap)",
    priority: "critical",
    tags: "mca,annual return,roc",
    conditionJson: field("businessType", "in", ["opc","pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "llp_form11",
    name: "LLP Form 11 — Annual Return",
    shortName: "LLP Form 11",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Annual return for LLP with details of partners and contribution.",
    howToComply: "File by 30 May every year (60 days after FY end).",
    frequency: "annually",
    dueDate: "30 May every year",
    penalty: "₹100/day (no cap)",
    priority: "critical",
    tags: "llp,mca,annual return",
    conditionJson: field("businessType", "==", "llp"),
  },
  {
    ruleKey: "llp_form8",
    name: "LLP Form 8 — Statement of Accounts",
    shortName: "LLP Form 8",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Annual statement of accounts and solvency for all LLPs.",
    howToComply: "File by 30 October every year (6 months after FY end).",
    frequency: "annually",
    dueDate: "30 October every year",
    penalty: "₹100/day (no cap)",
    priority: "critical",
    tags: "llp,mca,accounts",
    conditionJson: field("businessType", "==", "llp"),
  },
  {
    ruleKey: "statutory_audit",
    name: "Statutory Audit (Companies Act)",
    shortName: "Statutory Audit",
    category: "mca_roc",
    authority: "ICAI / MCA",
    description: "Annual financial audit by a registered CA — mandatory for all companies.",
    howToComply: "Appoint a registered CA/firm. Complete audit before AGM.",
    frequency: "annually",
    dueDate: "Before AGM",
    penalty: "Company and officers liable for fines",
    priority: "critical",
    tags: "audit,mca,mandatory",
    conditionJson: field("businessType", "in", ["opc","pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "board_meetings",
    name: "Board Meetings (Minimum 4 per year)",
    shortName: "Board Meetings",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Companies Act mandates at least 4 board meetings per year with no gap exceeding 120 days.",
    howToComply: "Issue proper notice, maintain agenda and minutes. Register minutes in minutes book.",
    frequency: "quarterly",
    dueDate: "At least every 120 days",
    penalty: "Officers in default: up to ₹1 Lakh fine",
    priority: "high",
    tags: "mca,board meeting,governance",
    conditionJson: field("businessType", "in", ["pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "agm",
    name: "Annual General Meeting (AGM)",
    shortName: "AGM",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Annual General Meeting of shareholders — most important annual governance requirement.",
    howToComply: "Hold AGM within 6 months of FY end. First AGM: within 9 months.",
    frequency: "annually",
    dueDate: "30 September (6 months after 31 March FY end)",
    penalty: "Up to ₹1 Lakh + ₹5,000/day for continuing default",
    priority: "high",
    tags: "mca,agm,governance",
    conditionJson: field("businessType", "in", ["pvt_ltd","public_ltd","section8"]),
  },
  {
    ruleKey: "dir3_kyc",
    name: "DIR-3 KYC — Director KYC",
    shortName: "DIR-3 KYC",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Annual KYC update for all directors and designated partners on MCA portal.",
    howToComply: "File DIR-3 KYC form by 30 September (free if filed on time).",
    frequency: "annually",
    dueDate: "30 September",
    penalty: "₹5,000 late fee; DIN gets deactivated",
    priority: "high",
    tags: "mca,director,kyc",
    conditionJson: field("businessType", "in", ["opc","pvt_ltd","public_ltd","section8","llp"]),
  },

  // ─── LABOUR LAWS ────────────────────────────────────────────────────────────
  {
    ruleKey: "pf_reg",
    name: "PF Registration (EPFO)",
    shortName: "EPF Registration",
    category: "labor_law",
    authority: "Employees' Provident Fund Organisation (EPFO)",
    description: "Mandatory for establishments with 20+ employees. Employer contributes 12% + Employee 12% of basic salary.",
    howToComply: "Register on EPFO Unified Portal. File monthly ECR (Electronic Challan cum Return).",
    frequency: "monthly",
    dueDate: "15th of every month",
    penalty: "Damages: 5–25% per annum + Interest @12% p.a.",
    registrationLink: "https://unifiedportal-emp.epfindia.gov.in",
    priority: "critical",
    tags: "pf,labor,epfo,monthly",
    conditionJson: field("employeeCount", ">=", 20),
  },
  {
    ruleKey: "esic_reg",
    name: "ESIC Registration",
    shortName: "ESI Registration",
    category: "labor_law",
    authority: "Employees' State Insurance Corporation (ESIC)",
    description: "Mandatory for 10+ employees earning up to ₹21,000/month. Employer: 3.25%, Employee: 0.75%.",
    howToComply: "Register on ESIC portal. Deposit monthly contributions. File half-yearly returns.",
    frequency: "monthly",
    dueDate: "15th of every month (contribution) | 15 Apr & 15 Oct (returns)",
    penalty: "Simple interest @12% p.a. + prosecution",
    registrationLink: "https://www.esic.in",
    priority: "critical",
    tags: "esic,labor,monthly",
    conditionJson: field("employeeCount", ">=", 10),
  },
  {
    ruleKey: "professional_tax",
    name: "Professional Tax Registration",
    shortName: "Professional Tax",
    category: "state_compliance",
    authority: "State Government (Commercial Tax Department)",
    description: "Deduct professional tax from employee salaries. State-specific rates (Karnataka: max ₹2,400/yr; Maharashtra: max ₹2,500/yr).",
    howToComply: "Register as employer on state portal. Deduct monthly. File monthly/annual return.",
    frequency: "monthly",
    dueDate: "Monthly (state-specific)",
    penalty: "State-specific penalty and interest",
    priority: "high",
    tags: "professional tax,state,labor",
    conditionJson: and(
      fieldRaw("employeeCount", ">", 0),
      fieldRaw("state", "in", ["Maharashtra","Karnataka","West Bengal","Gujarat","Tamil Nadu","Andhra Pradesh","Telangana","Madhya Pradesh","Assam"])
    ),
  },
  {
    ruleKey: "shops_est",
    name: "Shops & Establishment Registration",
    shortName: "S&E Registration",
    category: "state_compliance",
    authority: "State Labour Department",
    description: "State-wise mandatory registration for all commercial establishments. Regulates working hours, leaves, and holidays.",
    howToComply: "Apply on state labour department portal or office. Annual renewal as per state rules.",
    frequency: "one_time",
    dueDate: "Before commencing operations",
    penalty: "₹200 – ₹5,000 (state-specific)",
    priority: "critical",
    tags: "shops,establishment,state,labor",
    conditionJson: field("businessType", "in", ["partnership","proprietorship","llp","pvt_ltd","public_ltd","opc","section8"]),
  },
  {
    ruleKey: "gratuity",
    name: "Payment of Gratuity Act",
    shortName: "Gratuity",
    category: "labor_law",
    authority: "Labour Department",
    description: "Applicable for 10+ employees. Gratuity payable to employees with 5+ years of service. Amount = 15 days salary × years of service.",
    howToComply: "Display gratuity act notice. Maintain gratuity fund or group insurance. Pay within 30 days of separation.",
    frequency: "event_based",
    dueDate: "Within 30 days of separation",
    penalty: "Imprisonment up to 6 months + Fine",
    priority: "high",
    tags: "gratuity,labor,retirement benefits",
    conditionJson: field("employeeCount", ">=", 10),
  },
  {
    ruleKey: "payment_bonus",
    name: "Payment of Bonus Act",
    shortName: "Bonus Act",
    category: "labor_law",
    authority: "Labour Department",
    description: "Mandatory for 20+ employees. Minimum 8.33% bonus (max 20%) for employees earning up to ₹21,000/month.",
    howToComply: "Pay bonus within 8 months of FY close (typically by November). Maintain register Form D.",
    frequency: "annually",
    dueDate: "Within 8 months of FY end (by 30 November)",
    penalty: "Prosecution + Fine",
    priority: "high",
    tags: "bonus,labor,annual",
    conditionJson: field("employeeCount", ">=", 20),
  },
  {
    ruleKey: "minimum_wages",
    name: "Minimum Wages Act Compliance",
    shortName: "Minimum Wages",
    category: "labor_law",
    authority: "State Labour Department",
    description: "Cannot pay employees below state-notified minimum wages. Rates revised quarterly.",
    howToComply: "Check state-notified minimum wages regularly. Maintain wage slips and registers (Form I/II).",
    frequency: "as_applicable",
    dueDate: "Ongoing",
    penalty: "Fine up to ₹500 per offence; repeated violation: imprisonment",
    priority: "critical",
    tags: "minimum wages,labor,mandatory",
    conditionJson: field("employeeCount", ">", 0),
  },
  {
    ruleKey: "posh_act",
    name: "POSH Act — Internal Complaints Committee",
    shortName: "POSH / ICC",
    category: "labor_law",
    authority: "Ministry of Women & Child Development",
    description: "10+ employees: mandatory Internal Complaints Committee (ICC) for prevention of sexual harassment at workplace.",
    howToComply: "Form ICC with senior woman employee. Draft policy. File annual report by 31 January. Conduct awareness training.",
    frequency: "annually",
    dueDate: "31 January (Annual Report to District Officer)",
    penalty: "First offence: ₹50,000 | Repeat: ₹1 Lakh + possible license cancellation",
    priority: "high",
    tags: "posh,labor,compliance",
    conditionJson: field("employeeCount", ">=", 10),
  },
  {
    ruleKey: "contract_labour",
    name: "Contract Labour (Regulation & Abolition) Act",
    shortName: "Contract Labour Act",
    category: "labor_law",
    authority: "Labour Department",
    description: "Registration mandatory for principal employers engaging 20+ contract workers.",
    howToComply: "Register in Form I (principal employer). Contractor to obtain license in Form IV. Maintain register Form F.",
    frequency: "one_time",
    dueDate: "Before engaging contract labour",
    penalty: "Prosecution + Fine up to ₹1,000",
    priority: "medium",
    tags: "contract labour,labor",
    conditionJson: field("contractWorkers", ">=", 20),
  },
  {
    ruleKey: "lwf",
    name: "Labour Welfare Fund (LWF)",
    shortName: "Labour Welfare Fund",
    category: "state_compliance",
    authority: "State Labour Welfare Board",
    description: "State-specific contribution to Labour Welfare Fund by both employer and employee.",
    howToComply: "Register with State Labour Welfare Board. Deposit half-yearly or annual contribution.",
    frequency: "half_yearly",
    dueDate: "State-specific (usually June and December)",
    penalty: "State-specific penalty",
    priority: "medium",
    tags: "lwf,labor welfare,state",
    conditionJson: and(
      fieldRaw("employeeCount", ">", 0),
      fieldRaw("state", "in", ["Maharashtra","Karnataka","Gujarat","Punjab","Haryana","Madhya Pradesh","Tamil Nadu","Andhra Pradesh","Telangana","Goa","Kerala"])
    ),
  },
  {
    ruleKey: "maternity_benefit",
    name: "Maternity Benefit Act",
    shortName: "Maternity Benefit",
    category: "labor_law",
    authority: "Labour Department",
    description: "10+ employees: 26 weeks paid maternity leave mandatory. ESIC-covered establishments are exempt.",
    howToComply: "Implement maternity leave policy. Maintain registers. ESIC covered establishments need not comply separately.",
    frequency: "event_based",
    dueDate: "As applicable",
    penalty: "Fine up to ₹5,000; repeated: imprisonment",
    priority: "high",
    tags: "maternity,labor",
    conditionJson: field("employeeCount", ">=", 10),
  },

  // ─── FACTORY / MANUFACTURING ──────────────────────────────────────────────
  {
    ruleKey: "factory_license",
    name: "Factory License (Factories Act, 1948)",
    shortName: "Factory License",
    category: "industry_license",
    authority: "Chief Inspector of Factories (State)",
    description: "Mandatory for manufacturing premises: 10+ workers with power use, or 20+ workers without power.",
    howToComply: "Apply to State Factory Inspector in Form 2. Renew annually.",
    frequency: "annually",
    dueDate: "Before 31 December for renewal",
    penalty: "Imprisonment up to 2 years + Fine up to ₹2 Lakh",
    priority: "critical",
    tags: "factory,manufacturing,license",
    conditionJson: and(fieldRaw("hasManufacturing", "==", true), fieldRaw("employeeCount", ">=", 10)),
  },
  {
    ruleKey: "pollution_noc",
    name: "Pollution Control Board — Consent to Establish & Operate",
    shortName: "PCB NOC",
    category: "environmental",
    authority: "State Pollution Control Board (SPCB)",
    description: "Manufacturing/industrial units must obtain Consent to Establish (CTE) before setup and Consent to Operate (CTO) before production.",
    howToComply: "Apply on State PCB portal. Category (Red/Orange/Green/White) determines compliance level. Renew periodically.",
    frequency: "annually",
    dueDate: "Before establishing/operating",
    penalty: "Unit closure + Criminal prosecution under Environment Protection Act",
    priority: "critical",
    tags: "pollution,environmental,manufacturing",
    conditionJson: field("hasManufacturing", "==", true),
  },
  {
    ruleKey: "fire_noc",
    name: "Fire NOC — Fire Safety Certificate",
    shortName: "Fire NOC",
    category: "industry_license",
    authority: "State Fire Department",
    description: "Mandatory for factories, restaurants, hotels, hospitals, and educational institutions.",
    howToComply: "Apply to local fire department. Undergo fire safety audit. Install equipment. Renew annually.",
    frequency: "annually",
    dueDate: "Annual renewal",
    penalty: "Closure order + Fine",
    priority: "high",
    tags: "fire,noc,safety",
    conditionJson: or(
      fieldRaw("hasManufacturing", "==", true),
      fieldRaw("sector", "in", ["hospitality","healthcare","education"])
    ),
  },

  // ─── FOOD ─────────────────────────────────────────────────────────────────
  {
    ruleKey: "fssai_license",
    name: "FSSAI License / Registration",
    shortName: "FSSAI",
    category: "industry_license",
    authority: "Food Safety and Standards Authority of India (FSSAI)",
    description: "Mandatory for all food businesses. Basic registration (<₹12L), State license (₹12L–₹20Cr), Central license (>₹20Cr).",
    howToComply: "Apply on FoSCoS portal. Renew annually. File annual return.",
    frequency: "annually",
    dueDate: "Annual renewal before expiry",
    penalty: "Imprisonment up to 6 months + Fine up to ₹5 Lakh",
    registrationLink: "https://foscos.fssai.gov.in",
    priority: "critical",
    tags: "fssai,food,license",
    conditionJson: field("hasFood", "==", true),
  },
  {
    ruleKey: "fssai_return",
    name: "FSSAI Annual Return",
    shortName: "FSSAI Return",
    category: "industry_license",
    authority: "FSSAI",
    description: "Annual return mandatory for FSSAI State/Central license holders (turnover ≥ ₹12 Lakh).",
    howToComply: "File Form D-1 on FoSCoS portal by 31 May.",
    frequency: "annually",
    dueDate: "31 May",
    penalty: "₹100/day late fee",
    priority: "high",
    tags: "fssai,food,annual return",
    conditionJson: and(fieldRaw("hasFood", "==", true), fieldRaw("turnoverLakhs", ">=", 12)),
  },

  // ─── PHARMA ───────────────────────────────────────────────────────────────
  {
    ruleKey: "drug_license",
    name: "Drug License",
    shortName: "Drug License",
    category: "industry_license",
    authority: "State Drug Controller / CDSCO",
    description: "Mandatory for manufacturing, wholesale, or retail of drugs/medicines. Different forms for different activities.",
    howToComply: "Apply to State Drug Control Authority. Form 20/21 (retail), 20B/21B (wholesale), 25/28 (manufacturing). Annual renewal.",
    frequency: "annually",
    dueDate: "Annual renewal",
    penalty: "Imprisonment 3–5 years + Fine",
    priority: "critical",
    tags: "drug,pharma,license",
    conditionJson: field("hasPharma", "==", true),
  },

  // ─── IMPORT / EXPORT ──────────────────────────────────────────────────────
  {
    ruleKey: "iec",
    name: "IEC — Import Export Code",
    shortName: "IEC",
    category: "import_export",
    authority: "DGFT (Directorate General of Foreign Trade)",
    description: "Mandatory for all import/export activities. PAN-based 10-digit code. Lifetime valid, no renewal.",
    howToComply: "Apply on DGFT portal online. PAN-based. No renewal required.",
    frequency: "one_time",
    dueDate: null,
    penalty: "Cannot import/export without IEC",
    registrationLink: "https://www.dgft.gov.in",
    priority: "critical",
    tags: "iec,import,export,dgft",
    conditionJson: field("hasImportExport", "==", true),
  },
  {
    ruleKey: "rcmc",
    name: "RCMC — Export Promotion Council Registration",
    shortName: "RCMC",
    category: "import_export",
    authority: "Export Promotion Councils / FIEO / APEDA",
    description: "Required for availing export benefits, incentives, and authorizations from export promotion councils.",
    howToComply: "Apply to relevant EPC (FIEO, AEPC, APEDA, etc.). Annual renewal.",
    frequency: "annually",
    dueDate: "Annual renewal",
    penalty: "Cannot claim export incentives without RCMC",
    priority: "medium",
    tags: "rcmc,export,epc",
    conditionJson: field("hasImportExport", "==", true),
  },
  {
    ruleKey: "fema_compliance",
    name: "FEMA Compliance (Foreign Exchange)",
    shortName: "FEMA",
    category: "import_export",
    authority: "Reserve Bank of India (RBI)",
    description: "Mandatory filings for FDI, ECB, ODI, and other foreign exchange transactions through Authorized Dealer banks.",
    howToComply: "File FC-GPR (FDI received), FC-TRS (transfer of shares), FCGPR through AD bank on FIRMS portal.",
    frequency: "event_based",
    dueDate: "Within 30 days of receipt/transaction",
    penalty: "3× amount involved or ₹2 Lakh (whichever higher) + continuing default penalty",
    priority: "critical",
    tags: "fema,forex,rbi,fdi",
    conditionJson: field("hasForeignInvestment", "==", true),
  },

  // ─── MSME & STARTUP ───────────────────────────────────────────────────────
  {
    ruleKey: "udyam",
    name: "Udyam Registration (MSME)",
    shortName: "Udyam / MSME",
    category: "msme_startup",
    authority: "Ministry of MSME",
    description: "For Micro/Small/Medium enterprises: investment < ₹50 Cr and turnover < ₹250 Cr. Unlocks priority lending, government tenders, and subsidies.",
    howToComply: "Free registration on udyamregistration.gov.in using Aadhaar/PAN. No renewal required.",
    frequency: "one_time",
    dueDate: null,
    penalty: "No penalty — voluntary but highly beneficial",
    registrationLink: "https://udyamregistration.gov.in",
    priority: "medium",
    tags: "msme,udyam,registration",
    conditionJson: field("turnoverLakhs", "<=", 25000),
  },
  {
    ruleKey: "startup_dpiit",
    name: "Startup India — DPIIT Recognition",
    shortName: "DPIIT Startup",
    category: "msme_startup",
    authority: "DPIIT / Startup India",
    description: "For startups under 10 years old with turnover below ₹100 Crore. Benefits include tax exemptions (Sec 80-IAC), angel tax exemption, and easier compliance.",
    howToComply: "Register on startupindia.gov.in. Obtain DPIIT certificate. Then apply separately for Section 80-IAC tax exemption.",
    frequency: "one_time",
    dueDate: null,
    penalty: "No penalty — voluntary",
    registrationLink: "https://www.startupindia.gov.in",
    priority: "medium",
    tags: "startup,dpiit,tax benefit",
    conditionJson: and(fieldRaw("isStartup", "==", true), fieldRaw("turnoverLakhs", "<=", 10000)),
  },

  // ─── TRADE LICENSE & OTHERS ───────────────────────────────────────────────
  {
    ruleKey: "trade_license",
    name: "Trade License (Municipal Corporation)",
    shortName: "Trade License",
    category: "state_compliance",
    authority: "Municipal Corporation / Panchayat",
    description: "Permission from local authority to operate a business at a specific premises. Annual renewal.",
    howToComply: "Apply at local municipal corporation or gram panchayat. Annual renewal required.",
    frequency: "annually",
    dueDate: "Annual renewal before expiry",
    penalty: "Business closure + Fine",
    priority: "high",
    tags: "trade license,municipal,local",
    conditionJson: field("businessType", "in", ["partnership","proprietorship","llp","pvt_ltd","public_ltd","opc"]),
  },

  // ─── FINANCIAL SECTOR ─────────────────────────────────────────────────────
  {
    ruleKey: "nbfc_reg",
    name: "NBFC Registration (RBI)",
    shortName: "NBFC License",
    category: "financial_sector",
    authority: "Reserve Bank of India (RBI)",
    description: "Mandatory for Non-Banking Financial Companies. Minimum Net Owned Fund: ₹10 Crore.",
    howToComply: "Apply on RBI's Regulated Entities Portal (COSMOS). Detailed scrutiny process by RBI.",
    frequency: "one_time",
    dueDate: "Before commencing financial activities",
    penalty: "Prosecution + Cancellation of registration",
    priority: "critical",
    tags: "nbfc,rbi,finance,license",
    conditionJson: field("isNBFC", "==", true),
  },

  // ─── ENVIRONMENTAL ────────────────────────────────────────────────────────
  {
    ruleKey: "hazardous_waste",
    name: "Hazardous Waste Authorization",
    shortName: "HW Authorization",
    category: "environmental",
    authority: "State Pollution Control Board",
    description: "Mandatory authorization for units that generate, store, transport, or dispose of hazardous waste.",
    howToComply: "Apply in Form 1 to SPCB. File annual return. Follow manifest system for transport.",
    frequency: "annually",
    dueDate: "Annual renewal",
    penalty: "Imprisonment up to 5 years + Fine",
    priority: "critical",
    tags: "hazardous waste,environmental,manufacturing",
    conditionJson: field("hasHazardousWaste", "==", true),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ADVANCED RULES — Populated after "Know More" form
  // ══════════════════════════════════════════════════════════════════════════

  // ─── ADVANCED CENTRAL TAX ─────────────────────────────────────────────────
  {
    ruleKey: "tax_audit_44ab",
    name: "Tax Audit — Section 44AB (Form 3CA / 3CD)",
    shortName: "Tax Audit 44AB",
    category: "central_tax",
    authority: "Income Tax Department / ICAI",
    description: "Mandatory tax audit by CA if business turnover > ₹1 Crore (₹10 Crore if 95%+ digital transactions) or professional receipts > ₹50 Lakh. Report in Form 3CA/3CB & 3CD.",
    howToComply: "Get accounts audited by a practising CA. File Form 3CA/3CD (audited accounts) or 3CB/3CD before the due date. Must be completed before ITR filing.",
    frequency: "annually",
    dueDate: "30 September (or 31 October for companies with international transactions)",
    penalty: "0.5% of turnover or ₹1.5 Lakh (whichever less) — Section 271B",
    priority: "critical",
    tags: "tax audit,44ab,3CA,3CD,income tax",
    conditionJson: or(
      fieldRaw("turnoverLakhs", ">", 100),
      andRaw(fieldRaw("providesServices", "==", true), fieldRaw("turnoverLakhs", ">", 50))
    ),
  },
  {
    ruleKey: "form_15ca_cb",
    name: "Form 15CA / 15CB — Foreign Remittance Reporting",
    shortName: "Form 15CA/15CB",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Mandatory for any remittance to non-residents. Form 15CA (by payer online) + Form 15CB (CA certificate) required before bank processes outward foreign remittance exceeding ₹5 Lakh in a FY.",
    howToComply: "Before each foreign remittance: obtain Form 15CB from CA, then file Form 15CA on income tax e-filing portal. Submit both to the Authorised Dealer bank.",
    frequency: "event_based",
    dueDate: "Before each foreign remittance",
    penalty: "₹1 Lakh per default — Section 271-I",
    priority: "high",
    tags: "form 15CA,15CB,foreign remittance,non-resident,FEMA",
    conditionJson: field("makesForeignPayments", "==", true),
  },
  {
    ruleKey: "equalization_levy",
    name: "Equalization Levy — Digital Services Tax (6%)",
    shortName: "Equalization Levy",
    category: "central_tax",
    authority: "Income Tax Department (CBDT)",
    description: "6% Equalization Levy on payments to non-resident service providers for online advertisement, digital advertising space, and related digital services — when aggregate payment exceeds ₹1 Lakh per year to a single non-resident.",
    howToComply: "Deduct 6% from payments to non-resident digital service providers (e.g., Google Ads, Meta Ads). Deposit by 7th of the following month. File annual return (Form 1) by 30 June.",
    frequency: "monthly",
    dueDate: "7th of next month (deposit) | 30 June (Annual Return Form 1)",
    penalty: "1% per month interest on unpaid levy; penalty equal to levy amount; ₹1 Lakh for failure to file return",
    priority: "high",
    tags: "equalization levy,digital advertising,6%,non-resident,Google Ads,Meta",
    conditionJson: field("makesForeignPayments", "==", true),
  },
  {
    ruleKey: "vda_tax",
    name: "Virtual Digital Assets (Crypto/NFT) — Tax & TDS Compliance",
    shortName: "VDA / Crypto Tax",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "30% flat tax on VDA gains (Section 115BBH). 1% TDS on VDA purchases ≥ ₹10,000/year (Section 194S). No loss set-off between VDAs or against other income. No carry-forward of VDA losses. Crypto exchanges must register with FIU-IND under PMLA.",
    howToComply: "Maintain trade-by-trade records. Pay 30% + surcharge + cess on all gains. Deduct 1% TDS when buying VDA from another person. File Form 26QE (self-deduction). Report all transactions in Schedule VDA of ITR.",
    frequency: "annually",
    dueDate: "ITR filing deadline | TDS deposit by 30th of following month",
    penalty: "Interest 1% per month on TDS; penalty up to 100% of TDS amount; 30% + penalty on unreported VDA gains",
    priority: "high",
    tags: "VDA,crypto,bitcoin,ethereum,NFT,30% tax,TDS 194S",
    conditionJson: field("hasCryptoVDA", "==", true),
  },
  {
    ruleKey: "transfer_pricing_3ceb",
    name: "Transfer Pricing — Form 3CEB (TP Audit Report)",
    shortName: "TP / Form 3CEB",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Mandatory CA report (Form 3CEB) certifying arm's-length pricing for ALL international related-party transactions — no minimum threshold. Maintain contemporaneous TP documentation (FAR analysis, benchmarking, comparables).",
    howToComply: "Appoint a CA to conduct TP audit. Maintain TP documentation before ITR filing. File Form 3CEB by October 31. For specified domestic transactions > ₹20 Crore, same rules apply.",
    frequency: "annually",
    dueDate: "31 October (Assessment Year)",
    penalty: "2% of each undisclosed/unreported transaction value; ₹5 Lakh flat for non-reporting; 50–200% of tax on TP adjustment",
    priority: "critical",
    tags: "transfer pricing,3CEB,international transactions,arm's length,related party",
    conditionJson: field("intlTxnLakhs", ">", 0),
  },
  {
    ruleKey: "master_file_cbcr",
    name: "Master File (Form 3CEAA) & Country-by-Country Report",
    shortName: "Master File / CbCR",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Master File (Form 3CEAA) required if consolidated group revenue ≥ ₹500 Crore. Country-by-Country Report (Form 3CEAD) required if consolidated revenue ≥ ₹5,500 Crore (~USD 750M). Part of OECD BEPS 2.0 framework.",
    howToComply: "File Form 3CEAA (Part A & B) annually. File Form 3CEAC (CbCR notification) by ITR due date. If group parent entity in India with revenue ≥ ₹5,500 Crore, file Form 3CEAD (CbCR) within 12 months of group FY end.",
    frequency: "annually",
    dueDate: "By ITR filing due date (typically 30 November for international transactions)",
    penalty: "₹5 Lakh for Master File non-filing; ₹5,000–₹50,000 per day for CbCR non-filing",
    priority: "high",
    tags: "master file,CbCR,BEPS,3CEAA,3CEAD,multinational,OECD",
    conditionJson: field("groupRevCrore", ">=", 500),
  },

  // ─── ADVANCED MCA / ROC ───────────────────────────────────────────────────
  {
    ruleKey: "csr_compliance",
    name: "CSR — Committee, Policy, Spending & CSR-2 Filing",
    shortName: "CSR (Section 135)",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Applicable if net profit ≥ ₹5 Crore OR net worth ≥ ₹500 Crore OR turnover ≥ ₹1,000 Crore. Must spend 2% of average net profit (last 3 FY) on Schedule VII activities. Constitute CSR Committee (min 3 directors including 1 Independent). File CSR-2 annually.",
    howToComply: "1) Constitute CSR Committee (3 directors, 1 ID). 2) Formulate CSR Policy and publish on website. 3) Spend 2% of avg net profit on Schedule VII activities within FY. 4) Unspent amount: transfer to Special Account by April 30 (ongoing projects) or to PM Fund by Sep 30 (other projects). 5) File Form CSR-2 by March 31.",
    frequency: "annually",
    dueDate: "CSR spending by 31 March | CSR-2 filing by 31 March | Unspent transfer by 30 April / 30 September",
    penalty: "Company: min ₹1 Lakh to 2× unspent amount (max ₹1 Crore) | Officers: up to ₹2 Lakh",
    priority: "critical",
    tags: "CSR,Section 135,CSR-2,schedule VII,2%,net profit",
    conditionJson: or(
      fieldRaw("netProfitLakhs", ">=", 500),
      fieldRaw("netWorthCrore", ">=", 500),
      fieldRaw("turnoverLakhs", ">=", 100000)
    ),
  },
  {
    ruleKey: "dpt_3",
    name: "DPT-3 — Return of Deposits / Exempted Receipts",
    shortName: "DPT-3",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Annual return mandatory for ALL companies (private, public, OPC) reporting money received that is NOT classified as deposits — e.g., loans from directors, inter-company loans, advance from customers, security deposits. Penalties are severe.",
    howToComply: "File DPT-3 on MCA21 portal by 30 June every year. Report ALL outstanding non-deposit receipts as of 31 March. Get CA certification. Even if amount is NIL after adjustment, audit report needed.",
    frequency: "annually",
    dueDate: "30 June every year",
    penalty: "Company: up to ₹10 Crore | Every officer in default: up to ₹2 Crore + imprisonment up to 7 years",
    priority: "critical",
    tags: "DPT-3,deposits,return,annual,loans,MCA",
    conditionJson: field("businessType", "in", ["opc","pvt_ltd","public_ltd","section8","llp"]),
  },
  {
    ruleKey: "msme_form1",
    name: "MSME Form 1 — Half-Yearly Return (MSME Dues)",
    shortName: "MSME Form 1",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Every company / LLP with outstanding dues to MSME (Micro/Small) suppliers exceeding 45 days must file Form MSME-1 half-yearly on MCA21. Section 43B(h) Income Tax Act — MSME dues paid beyond 45 days are not deductible in the same year.",
    howToComply: "Identify all MSME suppliers (Udyam-registered). Track outstanding invoices. For any dues beyond 45 days, file Form MSME-1 on MCA21 portal. Due: April 30 (for Oct–Mar period) and October 31 (for Apr–Sep period).",
    frequency: "half_yearly",
    dueDate: "30 April (for Oct–Mar) | 31 October (for Apr–Sep)",
    penalty: "₹20,000 first violation | ₹1,000/day continuing default (up to ₹3 Lakh) | Section 43B(h): deduction disallowed",
    priority: "high",
    tags: "MSME,Form 1,MSME-1,dues,half-yearly,Section 43B",
    conditionJson: and(
      fieldRaw("hasMSMEDues", "==", true),
      fieldRaw("businessType", "in", ["pvt_ltd","public_ltd","opc","llp","section8"])
    ),
  },
  {
    ruleKey: "secretarial_audit",
    name: "Secretarial Audit — Form MR-3",
    shortName: "Secretarial Audit",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs / ICSI",
    description: "Mandatory annual secretarial audit by a Practicing Company Secretary (PCS) for: listed companies, public companies with paid-up capital ≥ ₹50 Crore, companies with turnover ≥ ₹250 Crore, and companies with outstanding loans ≥ ₹100 Crore.",
    howToComply: "Appoint a PCS. Get secretarial audit done for the FY. Annex Form MR-3 (Secretarial Audit Report) to Board's Report. Listed companies must also file Annual Secretarial Compliance Report (Reg. 24A SEBI LODR) within 60 days of FY end.",
    frequency: "annually",
    dueDate: "Before AGM (Board's Report) | 30 May for SEBI Reg. 24A (listed companies)",
    penalty: "Company: ₹1 Lakh–₹5 Lakh | Every officer: ₹25,000–₹1 Lakh",
    priority: "high",
    tags: "secretarial audit,MR-3,PCS,company secretary,listed",
    conditionJson: or(
      fieldRaw("isListed", "==", true),
      fieldRaw("turnoverLakhs", ">=", 25000)
    ),
  },

  // ─── SEBI / FINANCIAL SECTOR (LISTED COMPANIES) ────────────────────────────
  {
    ruleKey: "sebi_lodr_quarterly",
    name: "SEBI LODR — Quarterly Compliance Filings",
    shortName: "SEBI LODR Quarterly",
    category: "financial_sector",
    authority: "SEBI / Stock Exchanges (NSE/BSE)",
    description: "Listed companies must file: Quarterly financial results (within 45 days), Corporate Governance Report (within 21 days), Statement of Investor Complaints (within 21 days), and Shareholding Pattern (within 21 days) — with stock exchanges every quarter.",
    howToComply: "File via stock exchange portals (NSE NEAPS / BSE Listing Centre). Financial results must be approved by Board. Annual results: within 60 days of FY end. Results must be published on company website simultaneously.",
    frequency: "quarterly",
    dueDate: "Financial Results: 45 days (Q1–Q3), 60 days (Q4) | CG Report: 21 days | Shareholding Pattern: 21 days",
    penalty: "₹1,000–₹5,000/day for each filing delay; SEBI penalty up to ₹1 Crore per default",
    priority: "critical",
    tags: "SEBI LODR,quarterly,listed,financial results,compliance report",
    conditionJson: field("isListed", "==", true),
  },
  {
    ruleKey: "sebi_pit_code",
    name: "SEBI Insider Trading Code (PIT Regulations 2015)",
    shortName: "Insider Trading Code",
    category: "financial_sector",
    authority: "SEBI",
    description: "Listed companies must implement: (1) Code of Fair Disclosure for UPSI (Schedule A), (2) Code of Conduct for trading by designated persons (Schedule B), (3) Structured Digital Database (SDD) for tracking UPSI sharing, (4) Trading window restrictions.",
    howToComply: "Adopt PIT Code. Appoint Compliance Officer. Maintain SDD (tamper-proof, min 8 years). Close trading window during UPSI periods (typically from quarter end to 48 hrs after results). Require pre-clearance for trades > threshold. File disclosures (Form C, D, E) to stock exchange.",
    frequency: "as_applicable",
    dueDate: "Continuous; disclosures within 2 trading days of trigger",
    penalty: "Up to ₹25 Crore or 3× profit (whichever higher) | Imprisonment up to 10 years",
    priority: "critical",
    tags: "insider trading,SEBI PIT,UPSI,trading window,compliance officer",
    conditionJson: field("isListed", "==", true),
  },
  {
    ruleKey: "sebi_rscr",
    name: "Reconciliation of Share Capital Audit (RSCR)",
    shortName: "SEBI RSCR Audit",
    category: "financial_sector",
    authority: "SEBI / Depositories (NSDL/CDSL)",
    description: "Quarterly audit by Practicing CA or CS to reconcile issued share capital with depository records (NSDL/CDSL). Ensures no discrepancy between physical and demat shares. Filed with stock exchanges within 30 days of each quarter end.",
    howToComply: "Appoint a PCA or PCS. Conduct quarterly reconciliation of shares held in demat vs. physical vs. total issued capital. File report with all stock exchanges where listed.",
    frequency: "quarterly",
    dueDate: "Within 30 days of end of each quarter",
    penalty: "SEBI/Stock exchange penalties for non-filing; ₹1 Lakh to ₹1 Crore per default",
    priority: "high",
    tags: "RSCR,share capital audit,demat,NSDL,CDSL,listed",
    conditionJson: field("isListed", "==", true),
  },
  {
    ruleKey: "sebi_brsr",
    name: "SEBI BRSR — Business Responsibility & Sustainability Report",
    shortName: "BRSR",
    category: "financial_sector",
    authority: "SEBI",
    description: "Mandatory for top 1,000 listed companies (by market cap) from FY 2022-23. Part of Annual Report. Covers 9 National Guidelines on Responsible Business Conduct (NGRBC) principles — environment, social, governance. Core + Leadership disclosures.",
    howToComply: "Prepare BRSR aligned with SEBI's format (Circular SEBI/HO/CFD/CMD-2/P/CIR/2021/562). Include in Annual Report sent to shareholders. File with stock exchange. From FY 2024-25: BRSR Core disclosures with reasonable/limited assurance for top 150 companies.",
    frequency: "annually",
    dueDate: "Along with Annual Report (within 21 working days of AGM)",
    penalty: "Non-filing subject to SEBI adjudication; stock exchange fines",
    priority: "high",
    tags: "BRSR,ESG,sustainability,listed,top 1000,NGRBC",
    conditionJson: and(fieldRaw("isListed", "==", true), fieldRaw("turnoverLakhs", ">=", 50000)),
  },

  // ─── FOREIGN COMPLIANCE (NEW CATEGORY) ───────────────────────────────────
  {
    ruleKey: "fdi_fc_gpr",
    name: "FC-GPR — FDI Receipt Reporting to RBI",
    shortName: "FC-GPR (FDI Filing)",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI) — FIRMS Portal",
    description: "Mandatory filing within 30 days of allotment of equity instruments (shares, CCPS, CCDs) to foreign investors. Filed on FIRMS portal. Both inward remittance (within 30 days of receipt) and FC-GPR (within 30 days of allotment) must be filed.",
    howToComply: "File on RBI FIRMS portal (firms.rbi.org.in). Submit: FIRC/bank credit advice, KYC of foreign investor, valuation certificate from CA/SEBI registered valuer, Board resolution, CS certificate on compliance. Process via Authorized Dealer (AD) bank.",
    frequency: "event_based",
    dueDate: "Within 30 days of allotment of equity instruments",
    penalty: "Up to 3× amount involved OR ₹2 Lakh (whichever higher) + ₹5,000/day continuing default | Compoundable by RBI",
    priority: "critical",
    tags: "FC-GPR,FDI,FEMA,RBI,foreign investment,FIRMS portal",
    conditionJson: field("hasFDIReceived", "==", true),
  },
  {
    ruleKey: "fla_return",
    name: "FLA Return — Foreign Liabilities & Assets Annual Return",
    shortName: "FLA Return",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI)",
    description: "Every Indian company/LLP that has received FDI or made overseas investment (ODI) must file FLA Return annually by July 15 — even if no fresh investment occurred in the year. Filed directly on RBI's FLAIR portal.",
    howToComply: "File on RBI's FLAIR portal (flair.rbi.org.in) by July 15 each year. Report outstanding FDI liabilities and overseas investment assets as of March 31. Based on audited balance sheet if available, otherwise provisional data.",
    frequency: "annually",
    dueDate: "15 July every year",
    penalty: "Up to ₹2 Lakh + ₹5,000 per day continuing default | FEMA compounding available",
    priority: "critical",
    tags: "FLA return,FDI,ODI,RBI,FLAIR portal,annual return",
    conditionJson: or(fieldRaw("hasFDIReceived", "==", true), fieldRaw("hasOverseasSub", "==", true)),
  },
  {
    ruleKey: "fc_trs",
    name: "FC-TRS — Transfer of Shares between Resident & Non-Resident",
    shortName: "FC-TRS",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI)",
    description: "Required when shares are transferred between resident and non-resident (buying or selling). Seller (or buyer, in some cases) must file FC-TRS on FIRMS portal within 60 days of receipt of consideration or transfer of shares.",
    howToComply: "File FC-TRS on FIRMS portal via AD bank. Submit: share transfer deed, valuation report, FIRC/outward remittance evidence, KYC of parties, board resolution approving transfer. Ensure pricing follows FDI valuation norms.",
    frequency: "event_based",
    dueDate: "Within 60 days of receipt of consideration / date of transfer",
    penalty: "Up to 3× amount involved OR ₹2 Lakh + ₹5,000/day continuing | FEMA compounding",
    priority: "high",
    tags: "FC-TRS,share transfer,non-resident,FEMA,RBI,FIRMS",
    conditionJson: field("hasFDIReceived", "==", true),
  },
  {
    ruleKey: "odi_compliance",
    name: "ODI — Overseas Direct Investment Compliance",
    shortName: "ODI / Overseas Investment",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI)",
    description: "Indian companies/LLPs/individuals investing abroad (equity, debt, guarantee in foreign entity) must file Form FC (Overseas Investment) for each investment. Annual Performance Report (APR) must be filed by December 31 each year for each overseas entity.",
    howToComply: "File Form FC with RBI through AD bank for each ODI transaction. File Annual Performance Report (APR) by December 31 each year. Ensure overseas investment complies with FEMA (Overseas Investment) Rules, 2022 — max 400% of net worth for financial sector entities.",
    frequency: "event_based",
    dueDate: "Form FC: within prescribed time | APR: 31 December each year",
    penalty: "Up to 3× amount involved OR ₹2 Lakh + ₹5,000/day | FEMA compounding",
    priority: "critical",
    tags: "ODI,overseas investment,RBI,Form FC,APR,FEMA",
    conditionJson: or(fieldRaw("expandingAbroad", "==", true), fieldRaw("hasOverseasSub", "==", true)),
  },
  {
    ruleKey: "ecb_reporting",
    name: "ECB — External Commercial Borrowing Reporting",
    shortName: "ECB Reporting",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI)",
    description: "Companies borrowing from foreign sources (ECB/FCCB) must file: Form ECB (Loan Registration Number) before drawdown, and Form ECB-2 (monthly return) by 7th of each month. Minimum Average Maturity Period (MAMP) must be maintained.",
    howToComply: "File Form ECB on FIRMS portal via AD bank to get Loan Registration Number (LRN) before the first drawdown. File Form ECB-2 (monthly statement) by 7th of each month during loan tenure. Ensure end-use restrictions are followed.",
    frequency: "monthly",
    dueDate: "Form ECB: before first drawdown | ECB-2: 7th of every month",
    penalty: "Up to 3× amount involved + ₹5,000/day continuing default | FEMA compounding",
    priority: "high",
    tags: "ECB,external commercial borrowing,RBI,Form ECB,ECB-2,foreign loan",
    conditionJson: field("hasECBBorrowing", "==", true),
  },
  {
    ruleKey: "branch_lo_setup",
    name: "Branch / Liaison / Project Office — RBI Permission & ROC Compliance",
    shortName: "Branch/LO/PO India",
    category: "foreign_compliance",
    authority: "Reserve Bank of India (RBI) / MCA",
    description: "Foreign companies establishing Branch Office (BO), Liaison Office (LO), or Project Office (PO) in India need prior RBI approval (Form FNC). Annual compliances: file audited accounts with RoC (Form FC-3), statutory audit, Annual Activity Certificate (AAC) to RBI.",
    howToComply: "Apply in Form FNC to RBI via AD bank. After approval: register with local RoC. Annual: file Form FC-3 (audited accounts) within 6 months of FY end, Annual Activity Certificate (AAC) from CA/CS to AD bank by September 30. LO renewal every 3 years.",
    frequency: "annually",
    dueDate: "AAC: 30 September | FC-3 filing: within 6 months of FY end",
    penalty: "FEMA violations: 3× amount + ₹5,000/day; imprisonment for wilful contravention",
    priority: "critical",
    tags: "branch office,liaison office,project office,RBI,foreign company India,FNC",
    conditionJson: field("isForeignEntityIndia", "==", true),
  },
  {
    ruleKey: "lrs_tcs",
    name: "LRS — TCS on Foreign Remittances (Section 206C(1G))",
    shortName: "LRS TCS",
    category: "foreign_compliance",
    authority: "Income Tax Department",
    description: "TCS at 20% (from October 1, 2023) on Liberalised Remittance Scheme (LRS) remittances exceeding ₹7 Lakh per year for purposes other than education/medical. Banks/ADs collect TCS. Education loans from financial institutions: 0.5%; other education: 5% up to ₹7L, 5% above. Medical: 5%.",
    howToComply: "Banks/AD banks collect TCS at source. Individuals must declare purpose. TCS is adjustable against income tax liability. Collect TCS certificates from banks. No further compliance for the individual beyond declaration of purpose.",
    frequency: "event_based",
    dueDate: "TCS collected by bank at time of remittance",
    penalty: "Bank's obligation — not remitter's; but individuals should track TCS certificates",
    priority: "medium",
    tags: "LRS,TCS,foreign remittance,206C,education abroad,investments abroad",
    conditionJson: or(fieldRaw("expandingAbroad", "==", true), fieldRaw("makesForeignPayments", "==", true)),
  },
  {
    ruleKey: "fdi_fema_fdi_policy",
    name: "FDI Policy Compliance — Sectoral Caps & Reporting",
    shortName: "FDI Policy Compliance",
    category: "foreign_compliance",
    authority: "DPIIT / Reserve Bank of India",
    description: "Businesses with FDI must ensure: (1) Sector is open for FDI (automatic/approval route). (2) Sectoral caps followed (Defense: 74% auto; Banking: 74% auto; Insurance: 74% auto; Media: 26%-49%). (3) Downstream investment rules followed. (4) No payment of technical collaboration fees above permissible limits.",
    howToComply: "Review Consolidated FDI Policy issued by DPIIT. Check if sector requires FIPB/Cabinet approval or is under automatic route. For government approval sectors, file application with respective ministry. Ensure pricing guidelines under FEMA are followed.",
    frequency: "event_based",
    dueDate: "Before receiving FDI and at time of each subsequent investment",
    penalty: "FEMA penalties; compounding by RBI; possible reversal of investment",
    priority: "critical",
    tags: "FDI policy,sectoral caps,DPIIT,automatic route,approval route,FEMA",
    conditionJson: field("hasFDIReceived", "==", true),
  },

  // ─── ADVANCED IMPORT / EXPORT ─────────────────────────────────────────────
  {
    ruleKey: "gst_lut",
    name: "GST LUT — Letter of Undertaking (Annual Filing)",
    shortName: "GST LUT",
    category: "import_export",
    authority: "GST Department (GSTN)",
    description: "Exporters can export goods/services without paying IGST by filing an LUT (Letter of Undertaking) at the start of each financial year. Without LUT, exporters must pay IGST and then claim refund — LUT is more cash-flow friendly.",
    howToComply: "File LUT on GST portal (GST RFD-11) before first export of each financial year. Valid for the full FY. Must export goods within 3 months of issue. For services: provide services within 1 year. If not fulfilled, pay IGST with interest.",
    frequency: "annually",
    dueDate: "Before first export transaction of each FY (April 1 onwards)",
    penalty: "If LUT violated — IGST payment due + interest at 18% p.a.",
    priority: "high",
    tags: "LUT,GST,export,zero-rated,IGST,refund",
    conditionJson: field("hasImportExport", "==", true),
  },
  {
    ruleKey: "advance_auth_compliance",
    name: "Advance Authorisation / Export Obligation Compliance",
    shortName: "Advance Auth / EODC",
    category: "import_export",
    authority: "DGFT",
    description: "Advance Authorisation (AA) allows duty-free import of inputs for export production. Export Obligation must be fulfilled within 18 months. Export Obligation Discharge Certificate (EODC) must be obtained from DGFT after fulfillment.",
    howToComply: "Apply for AA on DGFT portal. Import inputs within validity. Fulfill export obligation within 18 months. File EODC application with DGFT after fulfilling EO. Maintain records for 3 years. Apply for re-validation if EO period extension needed.",
    frequency: "event_based",
    dueDate: "Export Obligation: within 18 months of AA issue | EODC: within 3 years of EO fulfillment",
    penalty: "If EO not met: customs duty on imports + interest + penalty; denial of future licences",
    priority: "high",
    tags: "advance authorisation,AA,export obligation,EODC,DGFT,duty-free",
    conditionJson: field("hasImportExport", "==", true),
  },

  // ─── ENVIRONMENTAL (ADVANCED) ─────────────────────────────────────────────
  {
    ruleKey: "ewaste_epr",
    name: "E-Waste EPR — Producer Responsibility (E-Waste Rules 2022)",
    shortName: "E-Waste EPR",
    category: "environmental",
    authority: "Central Pollution Control Board (CPCB)",
    description: "Producers, manufacturers, and importers of Electrical & Electronic Equipment (EEE) must register on CPCB EPR portal and meet annual collection/recycling targets. E-Waste Certificates (EWC) tradeable on CPCB portal. Annual return by June 30.",
    howToComply: "Register on CPCB EPR portal as producer/manufacturer/importer. Set annual collection targets (60%→70%→80% progressively). Tie up with registered recyclers/dismantlers. Obtain EWC (E-Waste Certificates). File annual return by June 30.",
    frequency: "annually",
    dueDate: "Annual return by 30 June",
    penalty: "Environmental Compensation (EC) per metric tonne of unmet EPR target; up to ₹1 Crore + facility closure",
    priority: "high",
    tags: "e-waste,EPR,CPCB,producer responsibility,EEE,electronics",
    conditionJson: or(
      fieldRaw("sector", "in", ["manufacturing","it_software"]),
      fieldRaw("hasManufacturing", "==", true)
    ),
  },

  // ─── DIGITAL COMPLIANCE (NEW CATEGORY) ────────────────────────────────────
  {
    ruleKey: "dpdp_act",
    name: "DPDP Act 2023 — Digital Personal Data Protection Compliance",
    shortName: "DPDP Act",
    category: "digital_compliance",
    authority: "Data Protection Board of India (Ministry of Electronics & IT)",
    description: "The Digital Personal Data Protection Act, 2023 (Presidential assent August 2023). Applies to all entities processing digital personal data in India or processing data of Indian residents. Key obligations: consent, notice, purpose limitation, data minimization, security safeguards, breach notification. Rules under finalization as of 2025.",
    howToComply: "1) Conduct data inventory — what personal data collected and for what purpose. 2) Implement consent framework with granular opt-in. 3) Create clear, accessible privacy notice in English + local language. 4) Establish data breach response plan — notify Board and affected individuals promptly. 5) Appoint Grievance Officer. 6) Implement retention/deletion policy.",
    frequency: "as_applicable",
    dueDate: "Rules not yet notified (as of mid-2025) — begin preparation now",
    penalty: "Up to ₹250 Crore for security breach | ₹200 Crore for breach notification failure | ₹150 Crore for Significant Data Fiduciary non-compliance",
    priority: "high",
    tags: "DPDP,data protection,privacy,consent,digital,personal data",
    conditionJson: field("collectsPersonalData", "==", true),
  },
  {
    ruleKey: "ecommerce_consumer_rules",
    name: "Consumer Protection (E-Commerce) Rules 2020",
    shortName: "E-Commerce Rules",
    category: "digital_compliance",
    authority: "Department of Consumer Affairs / CCPA",
    description: "Mandatory for all e-commerce platforms offering goods/services in India. Requires: mandatory disclosures (legal name, address, contact, GSTIN, PAN, country of origin), Grievance Officer (Indian resident), 48-hour complaint acknowledgement, 1-month resolution, published returns/refund policy, prohibition on flash sale manipulation.",
    howToComply: "1) Display all mandatory seller/platform information on website/app. 2) Appoint a Grievance Officer — publish name, designation, contact details. 3) Implement complaint tracking system. 4) Publish clear return/refund/exchange policy before purchase. 5) Marketplace entities: ensure sellers display their own information. 6) No manipulation of search results or reviews.",
    frequency: "as_applicable",
    dueDate: "Continuous — ongoing compliance",
    penalty: "₹10 Lakh (first offence) | ₹50 Lakh (repeat) under Consumer Protection Act | ₹10 Lakh/day for CCPA orders",
    priority: "high",
    tags: "e-commerce,consumer protection,grievance officer,online marketplace,mandatory disclosure",
    conditionJson: field("isEcomOperator", "==", true),
  },
  {
    ruleKey: "it_intermediary_rules",
    name: "IT (Intermediary Guidelines) Rules 2021 — Digital Platform Compliance",
    shortName: "IT Intermediary Rules",
    category: "digital_compliance",
    authority: "Ministry of Electronics & IT (MeitY)",
    description: "All online intermediaries (websites, apps, platforms, marketplaces) must: publish privacy policy, appoint Grievance Officer (Indian resident, name+contact on platform), acknowledge complaints in 24 hours, resolve in 15 days, retain user data for 180 days, take down unlawful content within 36 hours of government/court order.",
    howToComply: "1) Publish comprehensive Privacy Policy and Terms of Use. 2) Appoint a Grievance Officer — publish details. 3) Set up complaint management system. 4) Enable content takedown on government orders within 36 hours. 5) If users > 50 lakh: also appoint Chief Compliance Officer, Nodal Contact Person, and publish monthly compliance reports.",
    frequency: "as_applicable",
    dueDate: "Monthly compliance report (if significant social media intermediary) | Complaints: 24 hr acknowledgement, 15 days resolution",
    penalty: "Loss of safe harbor under Section 79 IT Act — platform becomes liable for third-party content; criminal liability for officers",
    priority: "high",
    tags: "IT rules,intermediary,grievance officer,online platform,social media,safe harbor",
    conditionJson: or(fieldRaw("isEcomOperator", "==", true), fieldRaw("collectsPersonalData", "==", true)),
  },

  // ─── LABOR LAW (ADVANCED) ─────────────────────────────────────────────────
  {
    ruleKey: "bocw_cess",
    name: "BOCW Cess — Building & Construction Workers Welfare Cess (1%)",
    shortName: "BOCW Cess",
    category: "labor_law",
    authority: "State Building & Other Construction Workers Welfare Board",
    description: "Every employer undertaking building/construction work worth more than ₹10 Lakh must pay BOCW Cess at 1% of total cost of construction (excluding land). Establishment with 10+ construction workers must register. Cess funds worker welfare — pension, medical, accident benefit.",
    howToComply: "Assess cess on total construction cost. Pay cess to local authority (municipal body/state board) at time of plan approval or before start. Register establishment with State BOCW Board within 60 days of commencement. Register all workers. Display registration certificate prominently.",
    frequency: "one_time",
    dueDate: "Before commencement of construction (cess payment) | Within 60 days of start (registration)",
    penalty: "₹1,000 fine for failure to register | Interest at 2% per month on unpaid cess + penalty",
    priority: "high",
    tags: "BOCW,construction workers,cess,1%,welfare board,construction",
    conditionJson: field("hasConstructionActivity", "==", true),
  },

  // ─── STATE COMPLIANCE (ADVANCED) ──────────────────────────────────────────
  {
    ruleKey: "rera_project",
    name: "RERA — Real Estate Project Registration",
    shortName: "RERA Registration",
    category: "state_compliance",
    authority: "State Real Estate Regulatory Authority (RERA)",
    description: "Mandatory for real estate developers/promoters: register every project with plot area > 500 sq.m or > 8 apartments (residential/commercial) with State RERA before launch, marketing, or booking. Maintain 70% of collected funds in separate escrow account. File quarterly progress reports.",
    howToComply: "Apply on State RERA portal before project launch. Get RERA registration number. Maintain designated escrow bank account (70% funds). File quarterly project updates. Get project registered even for phase-wise development.",
    frequency: "one_time",
    dueDate: "Before launching/marketing/advertising project",
    penalty: "Up to 10% of estimated project cost for non-registration | Imprisonment up to 3 years for continued default | ₹10,000/day for agents",
    priority: "critical",
    tags: "RERA,real estate,project registration,developer,promoter,escrow",
    conditionJson: field("hasRealEstateDev", "==", true),
  },
  {
    ruleKey: "fcra_registration",
    name: "FCRA Registration / Prior Permission (Foreign Contributions)",
    shortName: "FCRA",
    category: "state_compliance",
    authority: "Ministry of Home Affairs (MHA)",
    description: "NGOs/Section 8 Companies/Trusts/Societies that receive foreign contributions (from foreign sources — funds, securities, articles) must obtain FCRA Registration (for established NGOs with 3+ years) or Prior Permission (for specific one-time grants). File FC-3 annual return by December 31.",
    howToComply: "Apply on FCRA portal (fcraonline.nic.in). Only SBI NDMB account can receive FCRA funds. Annual return FC-3 (+ CA-certified FC-4) by December 31. Administrative expenses cap: 20% of foreign contributions. No sub-granting to other organizations. Registration valid 5 years — apply for renewal 6 months before expiry.",
    frequency: "annually",
    dueDate: "FC-3 Annual Return: 31 December | Renewal application: 6 months before expiry",
    penalty: "Imprisonment up to 5 years + fine for unauthorized receipt | ₹1 Lakh for return failure | Registration cancellation for violations",
    priority: "critical",
    tags: "FCRA,foreign contribution,NGO,Section 8,MHA,annual return,FC-3",
    conditionJson: and(
      fieldRaw("receivesForeignDonation", "==", true),
      fieldRaw("businessType", "in", ["section8","partnership","proprietorship"])
    ),
  },

  // ─── MSME / STARTUP (ADVANCED) ────────────────────────────────────────────
  {
    ruleKey: "gem_registration",
    name: "GeM Registration — Government e-Marketplace",
    shortName: "GeM Registration",
    category: "msme_startup",
    authority: "Government e-Marketplace (GeM) — Ministry of Commerce",
    description: "Sellers supplying goods/services to government departments, PSUs, and central/state government bodies should register on GeM portal. Mandatory for public procurement from MSMEs in many categories. Provides direct access to government buyers without tenders.",
    howToComply: "Register on gem.gov.in as Seller. Provide Aadhaar/PAN, business registration documents, bank account details. List your products/services with appropriate categorization and pricing. Keep documents updated for bid participation.",
    frequency: "one_time",
    dueDate: null,
    penalty: "No penalty — voluntary but essential for government supply business",
    registrationLink: "https://gem.gov.in",
    priority: "medium",
    tags: "GeM,government marketplace,procurement,tender,MSME",
    conditionJson: and(
      fieldRaw("turnoverLakhs", "<=", 25000),
      fieldRaw("providesServices", "==", true)
    ),
  },

  // ─── NBFC / FINANCIAL SECTOR (ADVANCED) ───────────────────────────────────
  {
    ruleKey: "nbfc_returns_rbi",
    name: "NBFC Returns to RBI — Quarterly & Annual",
    shortName: "NBFC RBI Returns",
    category: "financial_sector",
    authority: "Reserve Bank of India (RBI)",
    description: "NBFCs must file multiple returns with RBI: NBS-1 (quarterly returns for deposit-taking NBFCs), NBS-2 (Prudential Norms), NBS-7 (Capital Funds/Risk Assets), ALM Returns, CRILC (Large Borrower data), Fraud Reporting. Specific returns depend on NBFC category.",
    howToComply: "File through XBRL/COSMOS portal of RBI. NBS-1 quarterly by 15th of month following quarter end. ALM returns monthly. Annual returns by June 30. Keep up with RBI circulars as reporting requirements change frequently.",
    frequency: "quarterly",
    dueDate: "NBS-1: 15th after quarter end | Annual NBS: 30 June | ALM: Monthly",
    penalty: "Monetary penalty up to ₹1 Crore | Cancellation of registration for serious violations",
    priority: "critical",
    tags: "NBFC,RBI returns,NBS-1,ALM,COSMOS,prudential norms",
    conditionJson: field("isNBFC", "==", true),
  },
  {
    ruleKey: "pmla_reporting",
    name: "PMLA — Anti-Money Laundering Compliance (Reporting Entity)",
    shortName: "PMLA AML Compliance",
    category: "financial_sector",
    authority: "Financial Intelligence Unit — India (FIU-IND)",
    description: "NBFCs, real estate developers/agents (for transactions > ₹50 Lakh), CAs/CSs performing specified activities, jewellery dealers (> ₹10 Lakh), crypto exchanges — must comply with PMLA. Obligations: KYC/CDD, maintain records 5 years, file STR (Suspicious Transaction Reports) within 7 days, file CTR for cash > ₹10 Lakh.",
    howToComply: "Register as reporting entity on FIU-IND portal. Implement KYC/AML Policy. Appoint Principal Officer (compliance). File STRs within 7 days of suspicious transaction identification. File CTRs by 15th of next month. Maintain records for 5 years. Conduct periodic risk assessment.",
    frequency: "as_applicable",
    dueDate: "STR: within 7 working days | CTR: by 15th of next month | Records: 5 years",
    penalty: "Imprisonment 3–7 years + confiscation of property | ₹10,000/day for reporting failures | Up to ₹1 Lakh for non-compliance",
    priority: "critical",
    tags: "PMLA,AML,KYC,STR,CTR,FIU-IND,money laundering,reporting entity",
    conditionJson: or(
      fieldRaw("isNBFC", "==", true),
      fieldRaw("sector", "in", ["real_estate","finance_nbfc"]),
      fieldRaw("hasCryptoVDA", "==", true)
    ),
  },
];

async function main() {
  console.log("🌱 Seeding compliance rules...");

  for (const rule of RULES) {
    const docs = RULE_DOCUMENTS[rule.ruleKey] ?? [];
    const data = { ...rule, documentsJson: JSON.stringify(docs) };
    await prisma.complianceRule.upsert({
      where:  { ruleKey: rule.ruleKey },
      update: data,
      create: data,
    });
    process.stdout.write(".");
  }

  console.log(`\n✅ Seeded ${RULES.length} compliance rules`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
