import { ComplianceRule } from "./types";

export const COMPLIANCE_RULES: ComplianceRule[] = [

  // ─── CENTRAL TAX ───────────────────────────────────────────────────────────

  {
    id: "pan",
    name: "PAN Registration",
    shortName: "PAN",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Permanent Account Number — sabhi businesses ke liye mandatory tax identity",
    howToComply: "NSDL/UTIITSL portal pe online apply karo. Company/LLP ke liye separate PAN chahiye.",
    frequency: "one_time",
    penalty: "₹10,000 penalty if PAN not quoted where required (Sec 272B)",
    registrationLink: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    priority: "critical",
    condition: () => true,
    tags: ["tax", "registration", "mandatory"],
  },
  {
    id: "itr",
    name: "Income Tax Return (ITR) Filing",
    shortName: "ITR",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Annual income tax return — har business entity ke liye mandatory",
    howToComply: "ITR-3/4/5/6 (entity type ke hisaab se) file karo. Audit required if turnover > 1 Cr (business) ya 50L (professional).",
    frequency: "annually",
    dueDate: "31 July (non-audit) | 31 October (audit required)",
    penalty: "₹5,000 (late fee), interest @1% per month on tax due",
    registrationLink: "https://www.incometax.gov.in",
    priority: "critical",
    condition: () => true,
    tags: ["tax", "annual", "mandatory"],
  },
  {
    id: "tds_deduction",
    name: "TDS Deduction & Deposit",
    shortName: "TDS",
    category: "central_tax",
    authority: "Income Tax Department (TRACES)",
    description: "Tax Deducted at Source — salary, rent, professional fees, contractor payments pe TDS deduct karo",
    howToComply: "TAN register karo (form 49B). Har month 7 tarikh tak deposit karo. Quarterly return (24Q/26Q) file karo.",
    frequency: "monthly",
    dueDate: "7th of every month (deposit) | 31 July/Oct/Jan/May (quarterly return)",
    penalty: "1% per month interest for late deduction, 1.5% for late deposit. Penalty = TDS amount",
    priority: "critical",
    condition: (p) => p.employeeCount > 0 || p.turnoverLakhs > 20,
    tags: ["tax", "tds", "monthly"],
  },
  {
    id: "advance_tax",
    name: "Advance Tax Payment",
    shortName: "Advance Tax",
    category: "central_tax",
    authority: "Income Tax Department",
    description: "Estimated tax liability 10,000+ hone par quarterly advance tax deposit karna hoga",
    howToComply: "June 15 (15%), Sept 15 (45%), Dec 15 (75%), March 15 (100%) ke hisaab se pay karo",
    frequency: "quarterly",
    dueDate: "15 Jun, 15 Sep, 15 Dec, 15 Mar",
    penalty: "Interest @1% per month (Sec 234B & 234C) for shortfall",
    priority: "high",
    condition: (p) => p.turnoverLakhs > 10,
    tags: ["tax", "quarterly", "advance"],
  },

  // ─── GST ───────────────────────────────────────────────────────────────────

  {
    id: "gst_reg",
    name: "GST Registration",
    shortName: "GST Reg.",
    category: "central_tax",
    authority: "GST Department (GSTN)",
    description: "Goods & Services Tax registration — turnover limit cross hone ya inter-state supply karne par mandatory",
    howToComply: "GST portal pe online apply karo. Goods: 40L+, Services: 20L+ (special states: 10L). Inter-state: no threshold.",
    frequency: "one_time",
    penalty: "10% of tax evaded (min ₹10,000) | Deliberate: 100% penalty",
    registrationLink: "https://www.gst.gov.in/",
    priority: "critical",
    condition: (p) =>
      p.turnoverLakhs >= 20 ||
      p.hasImportExport ||
      p.hasMultipleStates,
    tags: ["gst", "registration", "indirect tax"],
  },
  {
    id: "gstr1",
    name: "GSTR-1 (Outward Supplies Return)",
    shortName: "GSTR-1",
    category: "central_tax",
    authority: "GST Department",
    description: "Sales/outward supplies ki details monthly ya quarterly file karo",
    howToComply: "Monthly: Turnover > 5Cr — 11th of next month. Quarterly (QRMP): Turnover < 5Cr — 13th of month after quarter.",
    frequency: "monthly",
    dueDate: "11th of next month (monthly) | 13th after quarter end (QRMP)",
    penalty: "₹200/day (₹100 CGST + ₹100 SGST), max ₹5,000",
    priority: "critical",
    condition: (p) => p.turnoverLakhs >= 20 || p.hasImportExport,
    tags: ["gst", "return", "monthly"],
  },
  {
    id: "gstr3b",
    name: "GSTR-3B (Summary Return & Tax Payment)",
    shortName: "GSTR-3B",
    category: "central_tax",
    authority: "GST Department",
    description: "Monthly summary return with tax payment — GST registered sabhi businesses ke liye",
    howToComply: "Monthly: 20th of next month. QRMP scheme: 22nd/24th of month after quarter.",
    frequency: "monthly",
    dueDate: "20th of next month",
    penalty: "₹50/day (nil return: ₹20/day), interest @18% pa on late tax payment",
    priority: "critical",
    condition: (p) => p.turnoverLakhs >= 20 || p.hasImportExport,
    tags: ["gst", "return", "monthly", "tax payment"],
  },
  {
    id: "gstr9",
    name: "GSTR-9 (Annual GST Return)",
    shortName: "GSTR-9",
    category: "central_tax",
    authority: "GST Department",
    description: "Annual GST return — full year ki consolidated summary",
    howToComply: "31 December tak file karo for previous FY. Turnover < 2Cr walo ke liye optional.",
    frequency: "annually",
    dueDate: "31 December",
    penalty: "₹200/day (max 0.5% of turnover)",
    priority: "high",
    condition: (p) => p.turnoverLakhs >= 200,
    tags: ["gst", "annual", "return"],
  },
  {
    id: "gstr9c",
    name: "GSTR-9C (GST Reconciliation / Audit)",
    shortName: "GSTR-9C",
    category: "central_tax",
    authority: "GST Department",
    description: "Turnover > 5 Crore — books aur GST return ki reconciliation statement",
    howToComply: "CA/CMA se certified reconciliation statement. 31 December tak file karo.",
    frequency: "annually",
    dueDate: "31 December",
    penalty: "₹200/day (max 0.5% of turnover)",
    priority: "high",
    condition: (p) => p.turnoverLakhs >= 500,
    tags: ["gst", "audit", "annual"],
  },

  // ─── MCA / ROC ─────────────────────────────────────────────────────────────

  {
    id: "roc_incorporation",
    name: "Company/LLP Incorporation (ROC)",
    shortName: "ROC Registration",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Company ya LLP ka MCA pe registration — ek baar karna hota hai",
    howToComply: "MCA21 portal pe SPICe+/FiLLiP form file karo. DIN, DSC, MOA, AOA required.",
    frequency: "one_time",
    registrationLink: "https://www.mca.gov.in",
    priority: "critical",
    condition: (p) =>
      ["llp", "opc", "pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["mca", "registration", "roc"],
  },
  {
    id: "aoc4",
    name: "AOC-4 — Financial Statement Filing",
    shortName: "AOC-4",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Annual financial statements (Balance Sheet, P&L) MCA pe file karo",
    howToComply: "AGM ke 30 days baad ya FY end ke 6 months baad (whichever earlier). AOC-4 form MCA portal pe.",
    frequency: "annually",
    dueDate: "30 days after AGM (usually by 29 October)",
    penalty: "₹100/day delay (no cap)",
    priority: "critical",
    condition: (p) =>
      ["opc", "pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["mca", "annual filing", "financial statements"],
  },
  {
    id: "mgt7",
    name: "MGT-7 / MGT-7A — Annual Return",
    shortName: "MGT-7",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "Company ki annual return — directors, shareholders, meetings ki details",
    howToComply: "AGM ke 60 days baad file karo. OPC/Small company: MGT-7A. Others: MGT-7.",
    frequency: "annually",
    dueDate: "60 days after AGM (usually by 28 November)",
    penalty: "₹100/day delay (no cap)",
    priority: "critical",
    condition: (p) =>
      ["opc", "pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["mca", "annual return", "roc"],
  },
  {
    id: "llp_form11",
    name: "LLP Form 11 — Annual Return",
    shortName: "LLP Form 11",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "LLP ki annual return — partners, contribution ki details",
    howToComply: "30 May tak file karo (FY end ke 60 days baad).",
    frequency: "annually",
    dueDate: "30 May every year",
    penalty: "₹100/day (no cap)",
    priority: "critical",
    condition: (p) => p.businessType === "llp",
    tags: ["llp", "mca", "annual return"],
  },
  {
    id: "llp_form8",
    name: "LLP Form 8 — Statement of Accounts",
    shortName: "LLP Form 8",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs (MCA)",
    description: "LLP ki financial statements — solvency statement ke saath",
    howToComply: "30 October tak file karo (FY end ke 6 months baad).",
    frequency: "annually",
    dueDate: "30 October every year",
    penalty: "₹100/day (no cap)",
    priority: "critical",
    condition: (p) => p.businessType === "llp",
    tags: ["llp", "mca", "accounts"],
  },
  {
    id: "statutory_audit",
    name: "Statutory Audit (Companies Act)",
    shortName: "Statutory Audit",
    category: "mca_roc",
    authority: "ICAI / MCA",
    description: "CA se annual financial statements ka audit — sabhi companies ke liye mandatory",
    howToComply: "Registered CA (individual/firm) se audit karwao. AGM se pehle complete karo.",
    frequency: "annually",
    dueDate: "Before AGM",
    priority: "critical",
    condition: (p) =>
      ["opc", "pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["audit", "mca", "mandatory"],
  },
  {
    id: "board_meetings",
    name: "Board Meetings (Min. 4 per year)",
    shortName: "Board Meetings",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Companies Act: minimum 4 board meetings per year (gap > 120 days nahi hona chahiye)",
    howToComply: "Proper notice, agenda, minutes maintain karo. Minutes book register karo.",
    frequency: "quarterly",
    penalty: "Officers in default: up to ₹1 Lakh",
    priority: "high",
    condition: (p) =>
      ["pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["mca", "board meeting", "governance"],
  },
  {
    id: "agm",
    name: "Annual General Meeting (AGM)",
    shortName: "AGM",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Annual General Meeting — shareholders ki sabse important meeting",
    howToComply: "FY end ke 6 months ke andar. First AGM: 9 months ke andar.",
    frequency: "annually",
    dueDate: "30 September (6 months after March 31 FY end)",
    penalty: "Up to ₹1 Lakh + ₹5000/day continuing default",
    priority: "high",
    condition: (p) =>
      ["pvt_ltd", "public_ltd", "section8"].includes(p.businessType),
    tags: ["mca", "agm", "governance"],
  },
  {
    id: "dir3_kyc",
    name: "DIR-3 KYC (Director KYC)",
    shortName: "DIR-3 KYC",
    category: "mca_roc",
    authority: "Ministry of Corporate Affairs",
    description: "Sabhi directors ka annual KYC MCA portal pe update karna hoga",
    howToComply: "30 September tak DIR-3 KYC form file karo (free if on time).",
    frequency: "annually",
    dueDate: "30 September",
    penalty: "₹5,000 if late — DIN deactivated",
    priority: "high",
    condition: (p) =>
      ["opc", "pvt_ltd", "public_ltd", "section8", "llp"].includes(p.businessType),
    tags: ["mca", "director", "kyc"],
  },

  // ─── LABOR LAWS ─────────────────────────────────────────────────────────────

  {
    id: "pf_reg",
    name: "PF Registration (EPFO)",
    shortName: "EPF Registration",
    category: "labor_law",
    authority: "Employees' Provident Fund Organisation (EPFO)",
    description: "20+ employees hone par PF registration mandatory. Employer 12% + Employee 12% contribution.",
    howToComply: "EPFO unified portal pe online register karo. Monthly ECR (Electronic Challan cum Return) file karo.",
    frequency: "monthly",
    dueDate: "15th of every month",
    penalty: "Damages: 5-25% per annum + Interest @12% pa",
    registrationLink: "https://unifiedportal-emp.epfindia.gov.in",
    priority: "critical",
    condition: (p) => p.employeeCount >= 20,
    tags: ["pf", "labor", "epfo", "monthly"],
  },
  {
    id: "esic_reg",
    name: "ESIC Registration",
    shortName: "ESI Registration",
    category: "labor_law",
    authority: "Employees' State Insurance Corporation (ESIC)",
    description: "10+ employees hone par ESIC mandatory. ₹21,000 tak salary wale employees covered. Employer: 3.25%, Employee: 0.75%.",
    howToComply: "ESIC portal pe register karo. Monthly contribution deposit karo. Half-yearly return file karo.",
    frequency: "monthly",
    dueDate: "15th of every month (contribution) | April 15 & October 15 (returns)",
    penalty: "Simple interest @12% pa + prosecution",
    registrationLink: "https://www.esic.in",
    priority: "critical",
    condition: (p) => p.employeeCount >= 10,
    tags: ["esic", "labor", "monthly"],
  },
  {
    id: "professional_tax",
    name: "Professional Tax Registration",
    shortName: "Professional Tax",
    category: "state_compliance",
    authority: "State Government (Commercial Tax Dept.)",
    description: "Employees ki salary pe professional tax deduct karo. State-specific rates. Karnataka: max ₹2,400/year, Maharashtra: max ₹2,500/year.",
    howToComply: "State government ke portal pe employer registration. Monthly salary deduction. Monthly/annual return.",
    frequency: "monthly",
    penalty: "State-specific — usually penalty + interest",
    priority: "high",
    condition: (p) =>
      p.employeeCount > 0 &&
      ["Maharashtra", "Karnataka", "West Bengal", "Gujarat", "Tamil Nadu", "Andhra Pradesh", "Telangana", "Madhya Pradesh", "Assam"].includes(p.state),
    tags: ["professional tax", "state", "labor"],
  },
  {
    id: "shops_est",
    name: "Shops & Establishment Registration",
    shortName: "S&E Registration",
    category: "state_compliance",
    authority: "State Labour Department",
    description: "Commercial establishment/shop ke liye state-wise mandatory registration. Working hours, leaves, holidays regulate karta hai.",
    howToComply: "State labour dept. ke portal ya office mein apply karo. Renewal annually or as per state rules.",
    frequency: "one_time",
    penalty: "₹200 - ₹5,000 (state-specific)",
    priority: "critical",
    condition: (p) =>
      ["partnership", "proprietorship", "llp", "pvt_ltd", "public_ltd", "opc", "section8"].includes(p.businessType),
    tags: ["shops", "establishment", "state", "labor"],
  },
  {
    id: "gratuity",
    name: "Payment of Gratuity Act Compliance",
    shortName: "Gratuity",
    category: "labor_law",
    authority: "Labour Department",
    description: "10+ employees hone par Gratuity Act applicable. 5+ saal service ke baad employee ko gratuity deni hoti hai.",
    howToComply: "Gratuity Act ki notice display karo. Amount = 15 days salary × years of service. Insurance ya fund maintain karo.",
    frequency: "event_based",
    penalty: "Imprisonment up to 6 months + Fine",
    priority: "high",
    condition: (p) => p.employeeCount >= 10,
    tags: ["gratuity", "labor", "retirement benefits"],
  },
  {
    id: "payment_bonus",
    name: "Payment of Bonus Act",
    shortName: "Bonus Act",
    category: "labor_law",
    authority: "Labour Department",
    description: "20+ employees: minimum 8.33% bonus mandatory (max 20%). ₹21,000 tak salary wale eligible.",
    howToComply: "Annual accounts ke 8 months baad bonus pay karo (usually October-November). Form D mein register maintain karo.",
    frequency: "annually",
    dueDate: "Within 8 months of FY close (November 30)",
    penalty: "Prosecution + Fine",
    priority: "high",
    condition: (p) => p.employeeCount >= 20,
    tags: ["bonus", "labor", "annual"],
  },
  {
    id: "minimum_wages",
    name: "Minimum Wages Act Compliance",
    shortName: "Minimum Wages",
    category: "labor_law",
    authority: "State Labour Department",
    description: "State-notified minimum wages se kum nahi pay kar sakte. Quarterly revision hoti hai.",
    howToComply: "State govt. ki notified minimum wages check karo. Wage slips maintain karo. Register Form I/II.",
    frequency: "as_applicable",
    priority: "critical",
    condition: (p) => p.employeeCount > 0,
    tags: ["minimum wages", "labor", "mandatory"],
  },
  {
    id: "posh_act",
    name: "POSH Act — Internal Complaints Committee",
    shortName: "POSH / ICC",
    category: "labor_law",
    authority: "Women & Child Development Ministry",
    description: "10+ employees: Sexual Harassment at Workplace Prevention Act — Internal Complaints Committee (ICC) mandatory",
    howToComply: "ICC form karo (senior woman employee + members). Policy draft karo. Annual report file karo (31 Jan). Training karo.",
    frequency: "annually",
    dueDate: "31 January (Annual Report)",
    penalty: "First offense: ₹50,000. Repeat: ₹1 Lakh + license cancellation",
    priority: "high",
    condition: (p) => p.employeeCount >= 10,
    tags: ["posh", "labor", "compliance"],
  },
  {
    id: "contract_labour",
    name: "Contract Labour (Regulation & Abolition) Act",
    shortName: "Contract Labour",
    category: "labor_law",
    authority: "Labour Department",
    description: "20+ contract workers employ karne wale establishments: registration mandatory",
    howToComply: "Form I mein registration (principal employer). Contractor: Form IV mein license. Register F maintain karo.",
    frequency: "one_time",
    penalty: "Prosecution + Fine up to ₹1,000",
    priority: "medium",
    condition: (p) => p.contractWorkers >= 20,
    tags: ["contract labour", "labor"],
  },
  {
    id: "lwf",
    name: "Labour Welfare Fund (LWF)",
    shortName: "Labour Welfare Fund",
    category: "state_compliance",
    authority: "State Labour Welfare Board",
    description: "State-specific labor welfare fund contribution — employer + employee dono contribute karte hain",
    howToComply: "State board pe register karo. Half-yearly ya annual contribution deposit karo.",
    frequency: "half_yearly",
    priority: "medium",
    condition: (p) =>
      p.employeeCount > 0 &&
      ["Maharashtra", "Karnataka", "Gujarat", "Punjab", "Haryana", "Madhya Pradesh", "Tamil Nadu", "Andhra Pradesh", "Telangana", "Goa", "Kerala"].includes(p.state),
    tags: ["lwf", "labor welfare", "state"],
  },
  {
    id: "maternity_benefit",
    name: "Maternity Benefit Act",
    shortName: "Maternity Benefit",
    category: "labor_law",
    authority: "Labour Department",
    description: "10+ employees wale establishments: 26 weeks paid maternity leave mandatory",
    howToComply: "Maternity leave policy implement karo. Register maintain karo. ESIC covered establishments exempt.",
    frequency: "event_based",
    priority: "high",
    condition: (p) => p.employeeCount >= 10,
    tags: ["maternity", "labor"],
  },

  // ─── FACTORY / MANUFACTURING ──────────────────────────────────────────────

  {
    id: "factory_license",
    name: "Factory License (Factories Act, 1948)",
    shortName: "Factory License",
    category: "industry_license",
    authority: "Chief Inspector of Factories (State)",
    description: "Power use karne wale: 10+ workers; Without power: 20+ workers. Manufacturing premises ke liye mandatory.",
    howToComply: "State Factory Inspector ke paas Form 2 mein apply karo. Annual renewal hoti hai.",
    frequency: "annually",
    penalty: "Imprisonment up to 2 years + Fine up to ₹2 Lakh",
    priority: "critical",
    condition: (p) => p.hasManufacturing && p.employeeCount >= 10,
    tags: ["factory", "manufacturing", "license"],
  },
  {
    id: "pollution_noc",
    name: "Pollution Control Board — Consent to Establish & Operate",
    shortName: "PCB NOC",
    category: "environmental",
    authority: "State Pollution Control Board (SPCB)",
    description: "Manufacturing/industrial units ke liye Consent to Establish (CTE) pehle, phir Consent to Operate (CTO) mandatory",
    howToComply: "State PCB portal pe apply karo. Category (Red/Orange/Green/White) ke hisaab se compliance level vary karta hai.",
    frequency: "annually",
    penalty: "Closure of unit + Criminal prosecution",
    priority: "critical",
    condition: (p) => p.hasManufacturing,
    tags: ["pollution", "environmental", "manufacturing"],
  },
  {
    id: "fire_noc",
    name: "Fire NOC",
    shortName: "Fire NOC",
    category: "industry_license",
    authority: "State Fire Department",
    description: "Factory, restaurant, hotel, hospital, educational institutions — Fire Safety Certificate mandatory",
    howToComply: "Local fire department ko application. Fire safety audit. Equipment installation. Annual renewal.",
    frequency: "annually",
    penalty: "Closure + Fine",
    priority: "high",
    condition: (p) =>
      p.hasManufacturing ||
      p.sector === "hospitality" ||
      p.sector === "healthcare" ||
      p.sector === "education",
    tags: ["fire", "noc", "safety"],
  },

  // ─── FOOD ──────────────────────────────────────────────────────────────────

  {
    id: "fssai_license",
    name: "FSSAI License / Registration",
    shortName: "FSSAI",
    category: "industry_license",
    authority: "Food Safety and Standards Authority of India (FSSAI)",
    description: "Koi bhi food business operate karne ke liye mandatory. Turnover ke hisaab se: Basic (<12L), State (12L-20Cr), Central (20Cr+)",
    howToComply: "FoSCoS portal pe online apply karo. Annual renewal. Annual return file karo.",
    frequency: "annually",
    dueDate: "31 May (Annual Return)",
    penalty: "Imprisonment up to 6 months + Fine up to ₹5 Lakh",
    registrationLink: "https://foscos.fssai.gov.in",
    priority: "critical",
    condition: (p) => p.hasFood,
    tags: ["fssai", "food", "license"],
  },
  {
    id: "fssai_return",
    name: "FSSAI Annual Return",
    shortName: "FSSAI Return",
    category: "industry_license",
    authority: "FSSAI",
    description: "FSSAI State/Central license holders: Annual return mandatory",
    howToComply: "FoSCoS portal pe Form D-1 file karo. 31 May tak.",
    frequency: "annually",
    dueDate: "31 May",
    penalty: "₹100/day",
    priority: "high",
    condition: (p) => p.hasFood && p.turnoverLakhs >= 12,
    tags: ["fssai", "food", "annual return"],
  },

  // ─── PHARMA / DRUG ─────────────────────────────────────────────────────────

  {
    id: "drug_license",
    name: "Drug License",
    shortName: "Drug License",
    category: "industry_license",
    authority: "State Drug Controller / CDSCO",
    description: "Drugs/medicines manufacturing, wholesale ya retail ke liye mandatory. Form 20/21 (retail), Form 20B/21B (wholesale), Form 25/28 (manufacturing).",
    howToComply: "State Drug Control Authority ko Form mein apply karo. Annual renewal.",
    frequency: "annually",
    penalty: "Imprisonment 3-5 years + Fine",
    priority: "critical",
    condition: (p) => p.hasPharma,
    tags: ["drug", "pharma", "license"],
  },

  // ─── IMPORT / EXPORT ───────────────────────────────────────────────────────

  {
    id: "iec",
    name: "IEC — Import Export Code",
    shortName: "IEC",
    category: "import_export",
    authority: "DGFT (Directorate General of Foreign Trade)",
    description: "Import ya export karne ke liye mandatory. PAN-based unique 10-digit code. One-time, lifetime valid.",
    howToComply: "DGFT portal pe online apply karo. PAN-based. No renewal required.",
    frequency: "one_time",
    registrationLink: "https://www.dgft.gov.in",
    priority: "critical",
    condition: (p) => p.hasImportExport,
    tags: ["iec", "import", "export", "dgft"],
  },
  {
    id: "rcmc",
    name: "RCMC — Export Promotion Council Registration",
    shortName: "RCMC",
    category: "import_export",
    authority: "Export Promotion Councils / APEDA / FIEO",
    description: "Export benefits, incentives aur authorizations ke liye RCMC mandatory. Sector-specific councils hain.",
    howToComply: "Relevant EPC (FIEO, AEPC, APEDA, etc.) mein apply karo. Annual renewal.",
    frequency: "annually",
    priority: "medium",
    condition: (p) => p.hasImportExport,
    tags: ["rcmc", "export", "epc"],
  },
  {
    id: "fema_compliance",
    name: "FEMA Compliance (Foreign Exchange)",
    shortName: "FEMA",
    category: "import_export",
    authority: "RBI / Authorized Dealer Banks",
    description: "Foreign investment, ECB, ODI, FDI ke liye FEMA compliance mandatory. Various RBI filings required.",
    howToComply: "AD Bank through filings. FC-GPR (FDI received), FC-TRS (transfer), FCGPR. FIRMS portal pe.",
    frequency: "event_based",
    penalty: "3x amount involved or ₹2 Lakh (whichever higher) + continuing default",
    priority: "critical",
    condition: (p) => p.hasForeignInvestment,
    tags: ["fema", "forex", "rbi", "fdi"],
  },

  // ─── MSME & STARTUP ────────────────────────────────────────────────────────

  {
    id: "udyam",
    name: "Udyam Registration (MSME)",
    shortName: "Udyam / MSME",
    category: "msme_startup",
    authority: "Ministry of MSME",
    description: "Micro/Small/Medium enterprise: investment < ₹50Cr and turnover < ₹250Cr. Multiple benefits — priority lending, government tenders.",
    howToComply: "udyamregistration.gov.in pe Aadhaar/PAN se free registration. No renewal needed.",
    frequency: "one_time",
    registrationLink: "https://udyamregistration.gov.in",
    priority: "medium",
    condition: (p) => p.turnoverLakhs <= 25000,
    tags: ["msme", "udyam", "registration"],
  },
  {
    id: "startup_dpiit",
    name: "Startup India (DPIIT Recognition)",
    shortName: "DPIIT Startup",
    category: "msme_startup",
    authority: "DPIIT / Startup India",
    description: "Startup: < 10 years old, turnover < ₹100Cr. Benefits: tax exemption (Sec 80-IAC), angel tax exemption, easier compliance.",
    howToComply: "startupindia.gov.in pe register karo. DPIIT certificate milega. Phir 80-IAC ke liye apply karo.",
    frequency: "one_time",
    registrationLink: "https://www.startupindia.gov.in",
    priority: "medium",
    condition: (p) => p.isStartup && p.turnoverLakhs <= 10000,
    tags: ["startup", "dpiit", "tax benefit"],
  },

  // ─── TRADE / MUNICIPAL ─────────────────────────────────────────────────────

  {
    id: "trade_license",
    name: "Trade License (Municipal Corporation)",
    shortName: "Trade License",
    category: "state_compliance",
    authority: "Municipal Corporation / Panchayat",
    description: "Local authority se business operate karne ki permission. Annual renewal.",
    howToComply: "Local municipal corporation / gram panchayat mein apply karo. Annual renewal.",
    frequency: "annually",
    penalty: "Business closure + Fine",
    priority: "high",
    condition: (p) =>
      ["partnership", "proprietorship", "llp", "pvt_ltd", "public_ltd", "opc"].includes(p.businessType),
    tags: ["trade license", "municipal", "local"],
  },

  // ─── FINANCIAL SECTOR ──────────────────────────────────────────────────────

  {
    id: "nbfc_reg",
    name: "NBFC Registration (RBI)",
    shortName: "NBFC License",
    category: "financial_sector",
    authority: "Reserve Bank of India (RBI)",
    description: "Non-Banking Financial Company: financial activities ke liye RBI registration mandatory. Min Net Owned Fund: ₹10 Crore.",
    howToComply: "RBI ke Regulated Entities Portal pe COSMOS application. Detailed process + RBI scrutiny.",
    frequency: "one_time",
    penalty: "Prosecution + Cancellation of registration",
    priority: "critical",
    condition: (p) => p.isNBFC,
    tags: ["nbfc", "rbi", "finance", "license"],
  },

  // ─── ENVIRONMENTAL ─────────────────────────────────────────────────────────

  {
    id: "hazardous_waste",
    name: "Hazardous Waste Authorization",
    shortName: "HW Authorization",
    category: "environmental",
    authority: "State Pollution Control Board",
    description: "Hazardous waste generate/store/dispose karne wale units: SPCB se authorization mandatory",
    howToComply: "Form 1 mein SPCB ko apply karo. Annual return file karo. Manifest system follow karo.",
    frequency: "annually",
    penalty: "Imprisonment up to 5 years + Fine",
    priority: "critical",
    condition: (p) => p.hasHazardousWaste,
    tags: ["hazardous waste", "environmental", "manufacturing"],
  },

];

export const CATEGORY_META: Record<string, {
  label: string; icon: string; color: string; bg: string; border: string;
}> = {
  central_tax: {
    label: "Central Tax Compliances",
    icon: "🏛️",
    color: "text-blue-700",
    bg: "bg-blue-50",
    border: "border-blue-200",
  },
  mca_roc: {
    label: "MCA / ROC Compliances",
    icon: "📋",
    color: "text-purple-700",
    bg: "bg-purple-50",
    border: "border-purple-200",
  },
  labor_law: {
    label: "Labour Law Compliances",
    icon: "👷",
    color: "text-orange-700",
    bg: "bg-orange-50",
    border: "border-orange-200",
  },
  industry_license: {
    label: "Industry Licenses & Registrations",
    icon: "📜",
    color: "text-green-700",
    bg: "bg-green-50",
    border: "border-green-200",
  },
  environmental: {
    label: "Environmental Compliances",
    icon: "🌿",
    color: "text-teal-700",
    bg: "bg-teal-50",
    border: "border-teal-200",
  },
  state_compliance: {
    label: "State-Specific Compliances",
    icon: "🗺️",
    color: "text-red-700",
    bg: "bg-red-50",
    border: "border-red-200",
  },
  import_export: {
    label: "Import / Export Compliances",
    icon: "🚢",
    color: "text-cyan-700",
    bg: "bg-cyan-50",
    border: "border-cyan-200",
  },
  msme_startup: {
    label: "MSME & Startup Registrations",
    icon: "🚀",
    color: "text-indigo-700",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
  },
  financial_sector: {
    label: "Financial Sector Compliances",
    icon: "🏦",
    color: "text-yellow-700",
    bg: "bg-yellow-50",
    border: "border-yellow-200",
  },
  foreign_compliance: {
    label: "Global / FEMA & Cross-Border",
    icon: "🌏",
    color: "text-sky-700",
    bg: "bg-sky-50",
    border: "border-sky-200",
  },
  digital_compliance: {
    label: "Digital, E-Commerce & Data Privacy",
    icon: "💻",
    color: "text-violet-700",
    bg: "bg-violet-50",
    border: "border-violet-200",
  },
};
